-- oracle dialect example — extended-reference pattern: read-heavy product catalog with duplicated brand lookup fields.

CREATE TABLE brands (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  country VARCHAR2(60) NOT NULL,
  website VARCHAR2(255)
);
CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  slug VARCHAR2(140) NOT NULL
);
CREATE TABLE suppliers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(160) NOT NULL,
  contact_email VARCHAR2(255) NOT NULL,
  lead_time_days NUMBER NOT NULL DEFAULT 7
);
CREATE TABLE warehouses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR2(20) NOT NULL,
  region VARCHAR2(40) NOT NULL,
  address_line VARCHAR2(200) NOT NULL
);
CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id NUMBER NOT NULL REFERENCES brands(id),
  category_id NUMBER NOT NULL REFERENCES categories(id),
  sku VARCHAR2(40) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  description CLOB,
  base_price_cents NUMBER NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD'
);
CREATE TABLE product_variants (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER NOT NULL REFERENCES products(id),
  variant_sku VARCHAR2(48) NOT NULL,
  barcode VARCHAR2(32),
  price_cents NUMBER NOT NULL,
  weight_grams NUMBER
);
CREATE TABLE supplier_products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id NUMBER NOT NULL REFERENCES suppliers(id),
  variant_id NUMBER NOT NULL REFERENCES product_variants(id),
  supplier_sku VARCHAR2(60) NOT NULL,
  cost_cents NUMBER NOT NULL
);
CREATE TABLE inventory_levels (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id NUMBER NOT NULL REFERENCES product_variants(id),
  warehouse_id NUMBER NOT NULL REFERENCES warehouses(id),
  quantity_on_hand NUMBER NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
