-- oracle dialect example — attribute pattern: EAV product_attributes on a normalized merchandising schema.

CREATE TABLE brands (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  country VARCHAR2(60) NOT NULL
);
CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  slug VARCHAR2(140) NOT NULL
);
CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id NUMBER NOT NULL REFERENCES brands(id),
  category_id NUMBER NOT NULL REFERENCES categories(id),
  sku VARCHAR2(40) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  description CLOB,
  base_price_cents NUMBER NOT NULL
);
CREATE TABLE product_variants (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER NOT NULL REFERENCES products(id),
  variant_sku VARCHAR2(48) NOT NULL,
  color VARCHAR2(40),
  size VARCHAR2(20),
  price_cents NUMBER NOT NULL
);
CREATE TABLE product_attributes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER NOT NULL REFERENCES products(id),
  attr_key VARCHAR2(60) NOT NULL,
  attr_value VARCHAR2(255) NOT NULL
);
CREATE TABLE reviews (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER NOT NULL REFERENCES products(id),
  stars NUMBER NOT NULL,
  body CLOB,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE inventory_levels (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id NUMBER NOT NULL REFERENCES product_variants(id),
  warehouse_code VARCHAR2(20) NOT NULL,
  quantity_on_hand NUMBER NOT NULL
);
