-- oracle dialect example — attribute pattern: EAV product_attributes collapsed into a key/value array.

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR2(40) NOT NULL,
  name VARCHAR2(200) NOT NULL
);
CREATE TABLE product_attributes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id NUMBER NOT NULL REFERENCES products(id),
  attr_key VARCHAR2(60) NOT NULL,
  attr_value VARCHAR2(255) NOT NULL
);
