-- sap-hana dialect example — computed pattern: account balances and counters maintained at write time.

CREATE TABLE accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number NVARCHAR(40) NOT NULL,
  current_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  amount NUMERIC(14,2) NOT NULL,
  posted_at TIMESTAMP NOT NULL
);
