-- sap-hana dialect example — computed pattern: ledger accounts with running balances and posting audit tables.

CREATE TABLE legal_entities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legal_name NVARCHAR(255) NOT NULL,
  tax_id NVARCHAR(40) NOT NULL,
  country CHAR(2) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT 1
);
CREATE TABLE accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES legal_entities(id),
  account_number NVARCHAR(40) NOT NULL,
  account_name NVARCHAR(160) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  current_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  opened_at TIMESTAMP NOT NULL
);
CREATE TABLE posting_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES legal_entities(id),
  batch_ref NVARCHAR(40) NOT NULL,
  status NVARCHAR(20) NOT NULL,
  submitted_at TIMESTAMP NOT NULL,
  posted_at TIMESTAMP
);
CREATE TABLE ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  batch_id INTEGER NOT NULL REFERENCES posting_batches(id),
  amount NUMERIC(14,2) NOT NULL,
  posting_type NVARCHAR(10) NOT NULL,
  memo NVARCHAR(255),
  posted_at TIMESTAMP NOT NULL
);
CREATE TABLE account_daily_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  snapshot_date DATE NOT NULL,
  opening_balance NUMERIC(14,2) NOT NULL,
  closing_balance NUMERIC(14,2) NOT NULL
);
CREATE TABLE audit_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES legal_entities(id),
  actor NVARCHAR(120) NOT NULL,
  action NVARCHAR(60) NOT NULL,
  occurred_at TIMESTAMP NOT NULL,
  details NCLOB
);
