-- sap-hana dialect example — outlier pattern: catalog products with skewed review volume and supporting merchandising tables.

CREATE TABLE brands (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name NVARCHAR(120) NOT NULL,
  country NVARCHAR(60) NOT NULL
);
CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name NVARCHAR(120) NOT NULL,
  slug NVARCHAR(140) NOT NULL
);
CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id INTEGER NOT NULL REFERENCES brands(id),
  category_id INTEGER NOT NULL REFERENCES categories(id),
  sku NVARCHAR(40) NOT NULL,
  name NVARCHAR(200) NOT NULL,
  base_price_cents INTEGER NOT NULL,
  review_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT 1
);
CREATE TABLE product_variants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id),
  variant_sku NVARCHAR(48) NOT NULL,
  color NVARCHAR(40),
  size NVARCHAR(20),
  price_cents INTEGER NOT NULL
);
CREATE TABLE reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id),
  reviewer_name NVARCHAR(120) NOT NULL,
  stars INTEGER NOT NULL,
  title NVARCHAR(200),
  body NCLOB,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE inventory_levels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id INTEGER NOT NULL REFERENCES product_variants(id),
  warehouse_code NVARCHAR(20) NOT NULL,
  quantity_on_hand INTEGER NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
