import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDdlToModel } from '../utilities/ddlParser.js';
import { enrichModelFromCsv } from '../utilities/csvModelEnrichment.js';
import { buildMigrationPlan } from '../design/patternSelector.js';
import { getProfile } from '../profiles/profiles.js';
import { buildDesignMeta, explainDesignRequest } from './runDesign.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const PERSONALIZATION_ROOT = join(ROOT, 'examples', 'personalization');

describe('runDesign buildDesignMeta', () => {
  it('reports folded tables when CSV enrichment enables embed patterns', () => {
    const ddl = readFileSync(join(PERSONALIZATION_ROOT, 'personalization.sql'), 'utf8');
    const raw = parseDdlToModel(ddl, 'ddl:oracle');
    const enriched = enrichModelFromCsv(raw, PERSONALIZATION_ROOT);
    const plan = buildMigrationPlan(enriched, getProfile('catalog'));
    const meta = buildDesignMeta(raw, enriched, plan, PERSONALIZATION_ROOT);

    expect(meta.hasRowStats).toBe(true);
    expect(meta.csvEnriched).toBe(true);
    expect(meta.collectionCount).toBeLessThan(meta.sqlTableCount);
    expect(meta.foldedTableCount).toBeGreaterThan(0);
  });

  it('shows 1:1 mapping without row stats on DDL-only model', () => {
    const ddl = readFileSync(join(ROOT, 'examples', 'iot', 'iot.sql'), 'utf8');
    const raw = parseDdlToModel(ddl, 'ddl:oracle');
    const plan = buildMigrationPlan(raw, getProfile('iot'));
    const meta = buildDesignMeta(raw, raw, plan);

    expect(meta.hasRowStats).toBe(false);
    expect(meta.collectionCount).toBe(meta.sqlTableCount);
    expect(meta.foldedTableCount).toBe(0);
  });

  it('applies API cardinality overrides before explaining a DDL-only design', () => {
    const ddl = `
      CREATE TABLE company_assets (
        asset_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asset_name VARCHAR(100) NOT NULL,
        location_id INT,
        CONSTRAINT fk_assets_location FOREIGN KEY (location_id) REFERENCES locations(location_id)
      );
    `;
    const raw = parseDdlToModel(ddl, 'ddl:oracle');
    const summary = explainDesignRequest({
      model: raw,
      profile: getProfile('ledger'),
      knowledgeDir: join(ROOT, 'knowledge'),
      cardinalityOverrides: {
        'locations::company_assets::location_id': 5,
      },
    });

    const locations = summary.collections.find((collection) => collection.sourceTable === 'locations');
    expect(locations?.embeddedFields).toContain('companyAssets');
    expect(summary.collectionCount).toBeLessThan(summary.sqlTableCount);
  });

  it('applies API force-embed overrides before explaining a DDL-only design', () => {
    const ddl = `
      CREATE TABLE company_assets (
        asset_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asset_name VARCHAR(100) NOT NULL,
        location_id INT,
        CONSTRAINT fk_assets_location FOREIGN KEY (location_id) REFERENCES locations(location_id)
      );
    `;
    const raw = parseDdlToModel(ddl, 'ddl:oracle');
    const summary = explainDesignRequest({
      model: raw,
      profile: getProfile('ledger'),
      knowledgeDir: join(ROOT, 'knowledge'),
      forceEmbedOverrides: {
        'locations::company_assets::location_id': true,
      },
    });

    const locations = summary.collections.find((collection) => collection.sourceTable === 'locations');
    expect(locations?.embeddedFields).toContain('companyAssets');
    expect(summary.collectionCount).toBeLessThan(summary.sqlTableCount);
  });

  it('applies API force-embed false overrides as separate collections', () => {
    const ddl = `
      CREATE TABLE customers (
        customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(100) NOT NULL
      );
      CREATE TABLE customer_addresses (
        address_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        street VARCHAR(200) NOT NULL,
        customer_id INT NOT NULL,
        CONSTRAINT fk_addresses_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
      );
    `;
    const raw = parseDdlToModel(ddl, 'ddl:oracle');
    const summary = explainDesignRequest({
      model: raw,
      profile: getProfile('catalog'),
      knowledgeDir: join(ROOT, 'knowledge'),
      forceEmbedOverrides: {
        'customers::customer_addresses::customer_id': false,
      },
    });

    const customers = summary.collections.find((collection) => collection.sourceTable === 'customers');
    const addresses = summary.collections.find((collection) => collection.sourceTable === 'customer_addresses');

    expect(customers?.embeddedFields ?? []).not.toContain('customerAddresses');
    expect(addresses).toBeDefined();
  });
});
