/**
 * Repository layer generator.
 *
 * Reads a migration plan and emits one TypeScript repository module per
 * collection, plus a shared connection module tuned to the workload profile
 * (pool sizing, socket timeouts, write concern).
 *
 * The generated code follows the concurrency-safety rules from the plan:
 *   - Computed pattern counters are maintained with $inc only.
 *   - Subset pattern arrays are maintained with $push + $position + $slice.
 *   - Bucket collections get an atomic upsert-and-append measurement writer.
 *   - There are NO application-side read-modify-write loops anywhere.
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CollectionPlan, MigrationPlan } from '../types.js';
import { toCamelCase, toPascalCase } from '../utilities/naming.js';

/** Options for one generation run. */
export type RepogenOptions = {
  /** Path to migration-plan.json. */
  planPath: string;
  /** Folder receiving the generated repository modules. */
  outDir: string;
};

/** Render the shared, profile-tuned MongoDB connection module. */
function renderClientModule(plan: MigrationPlan): string {
  return `/**
 * Shared MongoDB connection, tuned for the "${plan.profileId}" workload profile:
 * ${plan.telemetry.readPercent}:${plan.telemetry.writePercent} read:write at ${plan.telemetry.peakRpm.toLocaleString('en-US')} RPM (growth ${plan.telemetry.growthRate}).
 *
 * Generated by hvymetl repogen. Do not edit by hand; regenerate instead.
 */

import { MongoClient, type Db } from 'mongodb';

/** One client per process: the driver pools connections internally. */
let client: MongoClient | null = null;

/** Connect (once) and return the database handle. */
export async function getDb(uri: string, dbName: string): Promise<Db> {
  if (!client) {
    client = new MongoClient(uri, {
      // Pool sizing chosen for the workload's peak RPM.
      maxPoolSize: ${plan.pool.maxPoolSize},
      minPoolSize: ${plan.pool.minPoolSize},
      socketTimeoutMS: ${plan.pool.socketTimeoutMS},
      maxIdleTimeMS: ${plan.pool.maxIdleTimeMS},
      // Write concern chosen for the workload's durability needs.
      writeConcern: { w: ${JSON.stringify(plan.writeConcern.w)}, journal: ${plan.writeConcern.journal} },
    });
    await client.connect();
  }
  return client.db(dbName);
}

/** Close the shared client (call on graceful shutdown). */
export async function closeDb(): Promise<void> {
  if (client) {
    await client.close();
    client = null;
  }
}
`;
}

/** Map a $jsonSchema bsonType (or union with null) to a TypeScript type. */
function bsonTypeToTs(bsonType: string | string[] | undefined): string {
  if (bsonType === undefined) return 'unknown';
  if (Array.isArray(bsonType)) {
    const types = bsonType.map((single) => bsonTypeToTs(single));
    return [...new Set(types)].join(' | ');
  }
  switch (bsonType) {
    case 'string':
      return 'string';
    case 'int':
    case 'long':
    case 'double':
    case 'decimal':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'date':
      // The ETL imports dates as ISO-8601 strings; live writes may use Date.
      return 'Date | string';
    case 'array':
      return 'Document[]';
    case 'object':
      return 'Document';
    case 'null':
      return 'null';
    default:
      return 'unknown';
  }
}

/** Render the repository module for one collection plan. */
function renderRepositoryModule(collection: CollectionPlan): string {
  const pascalName = toPascalCase(collection.name);
  const parts: string[] = [];

  // Build the typed document shape from the plan's $jsonSchema, so the
  // driver's generics verify that $inc targets numbers, $push targets
  // arrays, and _id is the deterministic string the ETL produced.
  const schemaProperties = (collection.jsonSchema.properties ?? {}) as Record<string, { bsonType?: string | string[] }>;
  const requiredFields = new Set((collection.jsonSchema.required ?? []) as string[]);
  const typedFields = Object.entries(schemaProperties).map(([field, property]) => {
    const optionalMark = requiredFields.has(field) || field === 'schemaVersion' ? '' : '?';
    return `  ${field}${optionalMark}: ${bsonTypeToTs(property.bsonType)};`;
  });

  parts.push(`/**
 * Repository for the "${collection.name}" collection (source table: ${collection.sourceTable}).
 *
 * Generated by hvymetl repogen. Every update uses atomic modifiers so the
 * collection stays correct under concurrent writers; read-modify-write
 * loops are forbidden by design.
 */

import { type Collection, type Db, type Document } from 'mongodb';

/** The document shape, generated from the migration plan's $jsonSchema. */
export type ${pascalName}Document = {
${typedFields.join('\n')}
};

/** Get the typed collection handle. */
function collectionOf(db: Db): Collection<${pascalName}Document> {
  return db.collection<${pascalName}Document>('${collection.name}');
}

/** Fetch one document by its deterministic _id (an O(1) primary read). */
export async function find${pascalName}ById(db: Db, id: string): Promise<${pascalName}Document | null> {
  return collectionOf(db).findOne({ _id: id });
}

/** Page through the collection with an indexed sort on _id. */
export async function list${pascalName}(db: Db, afterId: string | null, pageSize: number): Promise<${pascalName}Document[]> {
  const filter = afterId ? { _id: { $gt: afterId } } : {};
  return collectionOf(db).find(filter).sort({ _id: 1 }).limit(pageSize).toArray();
}

/** Insert a new document, stamping the current schema version. */
export async function insert${pascalName}(db: Db, document: ${pascalName}Document): Promise<void> {
  await collectionOf(db).insertOne({ ...document, schemaVersion: 1 });
}

/** Set scalar fields atomically (never read-modify-write). */
export async function update${pascalName}Fields(db: Db, id: string, fields: Partial<${pascalName}Document>): Promise<void> {
  await collectionOf(db).updateOne({ _id: id }, { $set: fields });
}`);

  // Computed pattern: one $inc maintainer per counter.
  for (const computed of collection.computedFields) {
    const pascalField = toPascalCase(computed.field);
    parts.push(`
/**
 * Computed pattern maintainer for "${computed.field}" (${computed.description}).
 * $inc is atomic on the server, so concurrent writers can never lose counts.
 */
export async function increment${pascalField}(db: Db, id: string, delta = 1): Promise<void> {
  await collectionOf(db).updateOne({ _id: id }, { $inc: { ${computed.field}: delta } });
}`);
  }

  // Subset pattern: $push + $position + $slice keeps the newest N atomically.
  for (const arrayPlan of collection.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const pascalField = toPascalCase(arrayPlan.field);
    parts.push(`
/**
 * Subset pattern maintainer for "${arrayPlan.field}": inserts the new item
 * at the front and trims to ${arrayPlan.subsetLimit} in ONE atomic operation, so the
 * embedded array can never grow past its bound. The full history lives in
 * the "${arrayPlan.overflowCollection ?? arrayPlan.sourceTable}" collection.
 */
export async function pushTo${pascalField}(db: Db, id: string, item: Document): Promise<void> {
  await collectionOf(db).updateOne(
    { _id: id },
    { $push: { ${arrayPlan.field}: { $each: [item], $position: 0, $slice: ${arrayPlan.subsetLimit} } } },
  );
}`);
  }

  // Bucket pattern: the canonical atomic append-or-create measurement write.
  if (collection.bucket) {
    const groupField = toCamelCase(collection.bucket.groupByColumn);
    parts.push(`
/**
 * Bucket pattern writer: appends one measurement to its (source, window)
 * bucket, creating the bucket on first write. A single atomic upsert means
 * parallel writers at high RPM can never duplicate or drop a bucket.
 */
export async function record${pascalName}Measurement(
  db: Db,
  ${groupField}: string,
  measuredAt: Date,
  measurement: Document,
): Promise<void> {
  const windowMs = ${collection.bucket.windowMinutes} * 60000;
  const windowStart = new Date(Math.floor(measuredAt.getTime() / windowMs) * windowMs);
  const bucketId = \`\${${groupField}}|\${windowStart.toISOString().replace(/\\.\\d{3}Z$/, 'Z')}\`;
  await collectionOf(db).updateOne(
    { _id: bucketId },
    {
      $push: { ${collection.bucket.measurementsField}: measurement },
      $inc: { count: 1 },
      $setOnInsert: {
        schemaVersion: 1,
        ${groupField}: ${groupField},
        windowStart,
        windowMinutes: ${collection.bucket.windowMinutes},
      },
    },
    { upsert: true },
  );
}`);
  }

  // Extended Reference pattern: fan-out updater for duplicated lookup fields.
  for (const reference of collection.extendedReferences) {
    const pascalField = toPascalCase(reference.field);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonTypeToTs(schemaProperties[viaField]?.bsonType);
    parts.push(`
/**
 * Extended Reference fan-out: when the source "${reference.sourceTable}" record
 * changes, propagate the duplicated fields to every document referencing it.
 * Duplicated fields are chosen to change rarely, so this runs infrequently.
 */
export async function fanOut${pascalField}Update(db: Db, ${viaField}: ${viaType}, fields: Document): Promise<void> {
  const dotted: Document = {};
  for (const [key, value] of Object.entries(fields)) dotted[\`${reference.field}.\${key}\`] = value;
  await collectionOf(db).updateMany({ ${viaField}: ${viaField} }, { $set: dotted });
}`);
  }

  parts.push('');
  return parts.join('\n');
}

/** Render an ensure-indexes module covering every planned index. */
function renderIndexModule(plan: MigrationPlan): string {
  const lines: string[] = [];
  lines.push(`/**
 * Creates every index the migration plan specified. Run once at deploy time.
 * Generated by hvymetl repogen.
 */

import { type Db } from 'mongodb';

/** Ensure all planned indexes exist (createIndex is idempotent). */
export async function ensureIndexes(db: Db): Promise<void> {`);
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`  // ${index.reason}`);
      lines.push(
        `  await db.collection('${collection.name}').createIndex(${JSON.stringify(index.keys)}, { name: '${index.options.name}'${index.options.unique ? ', unique: true' : ''} });`,
      );
    }
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** Run the generator: one file per collection plus shared modules. */
export function runRepogen(options: RepogenOptions): void {
  const plan: MigrationPlan = JSON.parse(readFileSync(options.planPath, 'utf8'));
  mkdirSync(options.outDir, { recursive: true });

  const clientPath = join(options.outDir, 'mongoClient.ts');
  writeFileSync(clientPath, renderClientModule(plan));
  console.log(`Wrote ${clientPath}`);

  const indexPath = join(options.outDir, 'ensureIndexes.ts');
  writeFileSync(indexPath, renderIndexModule(plan));
  console.log(`Wrote ${indexPath}`);

  for (const collection of plan.collections) {
    const filePath = join(options.outDir, `${collection.name}Repository.ts`);
    writeFileSync(filePath, renderRepositoryModule(collection));
    console.log(`Wrote ${filePath}`);
  }

  console.log(`Generated ${plan.collections.length} repositories for profile "${plan.profileId}".`);
}
