import { describe, expect, it } from 'vitest';
import { parseDdlToModel } from './ddlParser.js';

const SAMPLE = `
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email VARCHAR(255) NOT NULL
);
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(200) NOT NULL
);
`;

const ORACLE_FK = `
CREATE TABLE payment_methods (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL UNIQUE,
    invoice_date DATE DEFAULT TRUNC NOT NULL,
    due_date DATE NOT NULL,
    total_due NUMBER(12,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID')),
    CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT chk_inv_due CHECK (due_date >= invoice_date)
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER NOT NULL,
    method_id NUMBER NOT NULL,
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
    CONSTRAINT fk_payments_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id)
);

CREATE TABLE customer_reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT fk_reviews_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_reviews_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);
`;

describe('parseDdlToModel', () => {
  it('parses multiple CREATE TABLE statements', () => {
    const model = parseDdlToModel(SAMPLE);
    expect(model.tables).toHaveLength(2);
    expect(model.tables[1].foreignKeys[0]?.referencesTable).toBe('users');
  });

  it('parses Oracle CONSTRAINT ... FOREIGN KEY lines', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const invoices = model.tables.find((t) => t.name === 'invoices');
    const payments = model.tables.find((t) => t.name === 'payments');
    const reviews = model.tables.find((t) => t.name === 'customer_reviews');

    expect(invoices?.foreignKeys).toEqual([
      { column: 'order_id', referencesTable: 'orders', referencesColumn: 'order_id' },
    ]);
    expect(payments?.foreignKeys).toEqual([
      { column: 'invoice_id', referencesTable: 'invoices', referencesColumn: 'invoice_id' },
      { column: 'method_id', referencesTable: 'payment_methods', referencesColumn: 'method_id' },
    ]);
    expect(reviews?.foreignKeys).toHaveLength(2);
  });

  it('creates stub tables for external FK targets so ER edges can render', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const tableNames = model.tables.map((t) => t.name);
    expect(tableNames).toContain('orders');
    expect(tableNames).toContain('customers');
    expect(tableNames).toContain('products');
    expect(model.relationships.length).toBeGreaterThanOrEqual(5);
  });

  it('parses Oracle column types and nullability', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const paymentMethods = model.tables.find((t) => t.name === 'payment_methods');
    expect(paymentMethods?.columns[0]).toMatchObject({
      name: 'method_id',
      sqlType: 'NUMBER',
      isPrimaryKey: true,
      nullable: false,
    });
    expect(paymentMethods?.columns[1]).toMatchObject({
      name: 'method_name',
      sqlType: 'VARCHAR2(30)',
      nullable: false,
    });
  });
});

const DB2_DDL = `
CREATE TABLE "SALES"."CUSTOMERS" (
  "CUSTOMER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE "SALES"."ORDERS" (
  "ORDER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "CUSTOMER_ID" INTEGER NOT NULL,
  "ORDER_DATE" DATE NOT NULL,
  CONSTRAINT FK_ORDERS_CUST FOREIGN KEY ("CUSTOMER_ID") REFERENCES "SALES"."CUSTOMERS" ("CUSTOMER_ID")
);
`;

const COCKROACH_DDL = `
CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  email STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INT8 NOT NULL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  total DECIMAL(12,2) NOT NULL
);
`;

const SPANNER_DDL = `
CREATE TABLE Singers (
  SingerId INT64 NOT NULL,
  FirstName STRING(1024),
  LastName STRING(1024),
  SingerInfo BYTES(MAX)
) PRIMARY KEY (SingerId);

CREATE TABLE Albums (
  SingerId INT64 NOT NULL,
  AlbumId INT64 NOT NULL,
  AlbumTitle STRING(MAX) NOT NULL
) PRIMARY KEY (SingerId, AlbumId),
  INTERLEAVE IN PARENT Singers ON DELETE CASCADE;
`;

describe('parseDdlToModel — additional dialects', () => {
  it('parses IBM Db2 schema-qualified tables and quoted FK references', () => {
    const model = parseDdlToModel(DB2_DDL, 'db2');
    expect(model.tables.map((t) => t.name)).toContain('SALES.CUSTOMERS');
    expect(model.tables.map((t) => t.name)).toContain('SALES.ORDERS');
    const orders = model.tables.find((t) => t.name === 'SALES.ORDERS');
    expect(orders?.foreignKeys).toEqual([
      { column: 'CUSTOMER_ID', referencesTable: 'CUSTOMERS', referencesColumn: 'CUSTOMER_ID' },
    ]);
  });

  it('parses CockroachDB IF NOT EXISTS and PostgreSQL-style types', () => {
    const model = parseDdlToModel(COCKROACH_DDL, 'cockroachdb');
    expect(model.tables).toHaveLength(2);
    const orders = model.tables.find((t) => t.name === 'orders');
    expect(orders?.columns[0]).toMatchObject({ name: 'id', sqlType: 'INT8', bsonType: 'long' });
    expect(orders?.foreignKeys[0]?.referencesTable).toBe('users');
  });

  it('parses Google Cloud Spanner trailing PRIMARY KEY and interleaved tables', () => {
    const model = parseDdlToModel(SPANNER_DDL, 'spanner');
    const singers = model.tables.find((t) => t.name === 'Singers');
    const albums = model.tables.find((t) => t.name === 'Albums');
    expect(singers?.primaryKey).toEqual(['SingerId']);
    expect(albums?.primaryKey).toEqual(['SingerId', 'AlbumId']);
    expect(singers?.columns[0]).toMatchObject({ name: 'SingerId', sqlType: 'INT64', bsonType: 'long' });
    expect(singers?.columns[3]).toMatchObject({ name: 'SingerInfo', sqlType: 'BYTES(MAX)', bsonType: 'binData' });
  });

  it('parses Amazon Aurora PostgreSQL DDL (PostgreSQL-compatible)', () => {
    const model = parseDdlToModel(SAMPLE, 'aurora-postgresql');
    expect(model.tables).toHaveLength(2);
  });
});
