import { describe, expect, it } from 'vitest';
import { parseDdlToModel } from './ddlParser.js';

const SAMPLE = `
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email VARCHAR(255) NOT NULL
);
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(200) NOT NULL
);
`;

const ORACLE_FK = `
CREATE TABLE payment_methods (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL UNIQUE,
    invoice_date DATE DEFAULT TRUNC NOT NULL,
    due_date DATE NOT NULL,
    total_due NUMBER(12,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID')),
    CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT chk_inv_due CHECK (due_date >= invoice_date)
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER NOT NULL,
    method_id NUMBER NOT NULL,
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
    CONSTRAINT fk_payments_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id)
);

CREATE TABLE customer_reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT fk_reviews_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_reviews_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);
`;

describe('parseDdlToModel', () => {
  it('parses multiple CREATE TABLE statements', () => {
    const model = parseDdlToModel(SAMPLE);
    expect(model.tables).toHaveLength(2);
    expect(model.tables[1].foreignKeys[0]?.referencesTable).toBe('users');
  });

  it('parses Oracle CONSTRAINT ... FOREIGN KEY lines', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const invoices = model.tables.find((t) => t.name === 'invoices');
    const payments = model.tables.find((t) => t.name === 'payments');
    const reviews = model.tables.find((t) => t.name === 'customer_reviews');

    expect(invoices?.foreignKeys).toEqual([
      { column: 'order_id', referencesTable: 'orders', referencesColumn: 'order_id' },
    ]);
    expect(payments?.foreignKeys).toEqual([
      { column: 'invoice_id', referencesTable: 'invoices', referencesColumn: 'invoice_id' },
      { column: 'method_id', referencesTable: 'payment_methods', referencesColumn: 'method_id' },
    ]);
    expect(reviews?.foreignKeys).toHaveLength(2);
  });

  it('creates stub tables for external FK targets so ER edges can render', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const tableNames = model.tables.map((t) => t.name);
    expect(tableNames).toContain('orders');
    expect(tableNames).toContain('customers');
    expect(tableNames).toContain('products');
    expect(model.relationships.length).toBeGreaterThanOrEqual(5);
  });

  it('parses Oracle column types and nullability', () => {
    const model = parseDdlToModel(ORACLE_FK, 'oracle');
    const paymentMethods = model.tables.find((t) => t.name === 'payment_methods');
    expect(paymentMethods?.columns[0]).toMatchObject({
      name: 'method_id',
      sqlType: 'NUMBER',
      isPrimaryKey: true,
      nullable: false,
    });
    expect(paymentMethods?.columns[1]).toMatchObject({
      name: 'method_name',
      sqlType: 'VARCHAR2(30)',
      nullable: false,
    });
  });
});
