import type { MigrationPlan } from '../../types.js';
import { toCamelCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToC } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `/*
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
 */
`;

function cGuard(name: string): string {
  return `HVYMETL_${name.toUpperCase().replace(/[^A-Z0-9]/g, '_')}_H`;
}

function renderIndexKeyAppends(keys: Record<string, number>, indent: string): string {
  return Object.entries(keys)
    .map(([key, direction]) => `${indent}BSON_APPEND_INT32 (keys, "${key}", ${direction});`)
    .join('\n');
}

function renderClient(plan: MigrationPlan): string {
  const guard = cGuard('mongo_client');
  return `${HEADER}
#ifndef ${guard}
#define ${guard}

#include <mongoc/mongoc.h>

mongoc_client_t *hvymetl_get_client (const char *uri);
void hvymetl_close_client (void);

#endif /* ${guard} */
`;
}

function renderClientSource(plan: MigrationPlan): string {
  return `${HEADER}
#include "mongo_client.h"

static mongoc_client_t *g_client = NULL;

mongoc_client_t *
hvymetl_get_client (const char *uri)
{
   if (!g_client) {
      g_client = mongoc_client_new (uri);
      if (g_client) {
         mongoc_client_set_max_pool_size (g_client, ${plan.pool.maxPoolSize});
         mongoc_client_set_min_pool_size (g_client, ${plan.pool.minPoolSize});
         mongoc_client_set_socket_timeout_ms (g_client, ${plan.pool.socketTimeoutMS});
         mongoc_client_set_max_idle_time_ms (g_client, ${plan.pool.maxIdleTimeMS});
      }
   }
   return g_client;
}

void
hvymetl_close_client (void)
{
   if (g_client) {
      mongoc_client_destroy (g_client);
      g_client = NULL;
   }
}
`;
}

function renderIndexesHeader(): string {
  const guard = cGuard('ensure_indexes');
  return `${HEADER}
#ifndef ${guard}
#define ${guard}

#include <mongoc/mongoc.h>

bool hvymetl_ensure_indexes (mongoc_client_t *client, const char *db_name, bson_error_t *error);

#endif /* ${guard} */
`;
}

function renderIndexesSource(plan: MigrationPlan): string {
  const blocks: string[] = [];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      const fn = `hvymetl_build_index_${collection.name}_${index.options.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
      blocks.push(`static void
${fn} (bson_t *keys)
{
   bson_init (keys);
${renderIndexKeyAppends(index.keys, '   ')}
}
`);
    }
  }

  const ensureLines: string[] = [
    `${HEADER}
#include "ensure_indexes.h"

${blocks.join('\n')}
bool
hvymetl_ensure_indexes (mongoc_client_t *client, const char *db_name, bson_error_t *error)
{
   mongoc_collection_t *collection;
`,
  ];

  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      const fn = `hvymetl_build_index_${collection.name}_${index.options.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
      ensureLines.push(`   /* ${index.reason} */`);
      ensureLines.push(`   {`);
      ensureLines.push(`      bson_t keys;`);
      ensureLines.push(`      mongoc_index_opt_t opt;`);
      ensureLines.push(`      ${fn} (&keys);`);
      ensureLines.push(`      mongoc_index_opt_init (&opt);`);
      ensureLines.push(`      opt.name = "${index.options.name}";`);
      if (index.options.unique) {
        ensureLines.push(`      opt.unique = true;`);
      }
      ensureLines.push(
        `      collection = mongoc_client_get_collection (client, db_name, "${collection.name}");`,
      );
      ensureLines.push(
        `      if (!mongoc_collection_create_index (collection, &keys, &opt, error)) {`,
      );
      ensureLines.push(`         mongoc_collection_destroy (collection);`);
      ensureLines.push(`         bson_destroy (&keys);`);
      ensureLines.push(`         return false;`);
      ensureLines.push(`      }`);
      ensureLines.push(`      mongoc_collection_destroy (collection);`);
      ensureLines.push(`      bson_destroy (&keys);`);
      ensureLines.push(`   }`);
    }
  }

  ensureLines.push(`   return true;`);
  ensureLines.push(`}`);
  ensureLines.push('');
  return ensureLines.join('\n');
}

function renderRepositoryHeader(spec: CollectionCodegenSpec): string {
  const guard = cGuard(`${spec.name}_repository`);
  const fieldComments = spec.fields
    .map((field) => ` *   ${field.name}: ${bsonToC(field.bsonType)}`)
    .join('\n');

  const decls: string[] = [
    `mongoc_collection_t *${spec.camelName}_collection (mongoc_client_t *client, const char *db_name);`,
    `bson_t *${spec.camelName}_find_by_id (mongoc_client_t *client, const char *db_name, const char *id, bson_error_t *error);`,
    `mongoc_cursor_t *${spec.camelName}_list (mongoc_client_t *client, const char *db_name, const char *after_id, int page_size, bson_error_t *error);`,
    `bool ${spec.camelName}_insert (mongoc_client_t *client, const char *db_name, const bson_t *document, bson_error_t *error);`,
    `bool ${spec.camelName}_update_fields (mongoc_client_t *client, const char *db_name, const char *id, const bson_t *fields, bson_error_t *error);`,
  ];

  for (const computed of spec.computedFields) {
    decls.push(
      `bool ${spec.camelName}_increment_${computed.field} (mongoc_client_t *client, const char *db_name, const char *id, int64_t delta, bson_error_t *error);`,
    );
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    decls.push(
      `bool ${spec.camelName}_push_to_${arrayPlan.field} (mongoc_client_t *client, const char *db_name, const char *id, const bson_t *item, bson_error_t *error);`,
    );
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    decls.push(
      `bool ${spec.camelName}_record_measurement (mongoc_client_t *client, const char *db_name, const char *${groupField}, int64_t measured_at_ms, const bson_t *measurement, bson_error_t *error);`,
    );
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    decls.push(
      `bool ${spec.camelName}_fan_out_${reference.field}_update (mongoc_client_t *client, const char *db_name, const char *${viaField}, const bson_t *fields, bson_error_t *error);`,
    );
  }

  return `${HEADER}
#ifndef ${guard}
#define ${guard}

#include <mongoc/mongoc.h>
#include <stdint.h>
#include <stdbool.h>

/*
 * Repository for "${spec.name}" (source table: ${spec.sourceTable}).
 * Document fields:
${fieldComments}
 */

${decls.join('\n')}

#endif /* ${guard} */
`;
}

function renderRepositorySource(spec: CollectionCodegenSpec): string {
  const parts: string[] = [
    `${HEADER}
#include "${spec.name}_repository.h"
#include <stdio.h>
#include <string.h>
#include <time.h>

mongoc_collection_t *
${spec.camelName}_collection (mongoc_client_t *client, const char *db_name)
{
   return mongoc_client_get_collection (client, db_name, "${spec.name}");
}

bson_t *
${spec.camelName}_find_by_id (mongoc_client_t *client, const char *db_name, const char *id, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "_id", id);
   bson_t *doc = mongoc_collection_find_one (collection, &filter, NULL, NULL, NULL, error);
   bson_destroy (&filter);
   mongoc_collection_destroy (collection);
   return doc;
}

mongoc_cursor_t *
${spec.camelName}_list (mongoc_client_t *client, const char *db_name, const char *after_id, int page_size, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   if (after_id) {
      bson_t gt_doc;
      BSON_APPEND_UTF8 (&gt_doc, "$gt", after_id);
      BSON_APPEND_DOCUMENT (&filter, "_id", &gt_doc);
      bson_destroy (&gt_doc);
   }
   bson_t opts = BSON_INITIALIZER;
   BSON_APPEND_INT32 (&opts, "limit", page_size);
   {
      bson_t sort;
      BSON_APPEND_INT32 (&sort, "_id", 1);
      BSON_APPEND_DOCUMENT (&opts, "sort", &sort);
      bson_destroy (&sort);
   }
   mongoc_cursor_t *cursor = mongoc_collection_find_with_opts (collection, &filter, &opts, NULL);
   bson_destroy (&filter);
   bson_destroy (&opts);
   mongoc_collection_destroy (collection);
   return cursor;
}

bool
${spec.camelName}_insert (mongoc_client_t *client, const char *db_name, const bson_t *document, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t payload = BSON_INITIALIZER;
   bson_copy_to (document, false, &payload);
   BSON_APPEND_INT32 (&payload, "schemaVersion", 1);
   bool ok = mongoc_collection_insert_one (collection, &payload, NULL, NULL, error);
   bson_destroy (&payload);
   mongoc_collection_destroy (collection);
   return ok;
}

bool
${spec.camelName}_update_fields (mongoc_client_t *client, const char *db_name, const char *id, const bson_t *fields, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "_id", id);
   bson_t update = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&update, "$set", fields);
   bool ok = mongoc_collection_update_one (collection, &filter, &update, NULL, NULL, error);
   bson_destroy (&filter);
   bson_destroy (&update);
   mongoc_collection_destroy (collection);
   return ok;
}
`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
bool
${spec.camelName}_increment_${computed.field} (mongoc_client_t *client, const char *db_name, const char *id, int64_t delta, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "_id", id);
   bson_t inc_doc = BSON_INITIALIZER;
   BSON_APPEND_INT64 (&inc_doc, "${computed.field}", delta);
   bson_t update = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&update, "$inc", &inc_doc);
   bool ok = mongoc_collection_update_one (collection, &filter, &update, NULL, NULL, error);
   bson_destroy (&filter);
   bson_destroy (&inc_doc);
   bson_destroy (&update);
   mongoc_collection_destroy (collection);
   return ok;
}
`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
bool
${spec.camelName}_push_to_${arrayPlan.field} (mongoc_client_t *client, const char *db_name, const char *id, const bson_t *item, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "_id", id);
   bson_t each_array = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&each_array, "0", item);
   bson_t push_inner = BSON_INITIALIZER;
   BSON_APPEND_ARRAY (&push_inner, "$each", &each_array);
   BSON_APPEND_INT32 (&push_inner, "$position", 0);
   BSON_APPEND_INT32 (&push_inner, "$slice", ${arrayPlan.subsetLimit});
   bson_t push_doc = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&push_doc, "${arrayPlan.field}", &push_inner);
   bson_t update = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&update, "$push", &push_doc);
   bool ok = mongoc_collection_update_one (collection, &filter, &update, NULL, NULL, error);
   bson_destroy (&filter);
   bson_destroy (&each_array);
   bson_destroy (&push_inner);
   bson_destroy (&push_doc);
   bson_destroy (&update);
   mongoc_collection_destroy (collection);
   return ok;
}
`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
bool
${spec.camelName}_record_measurement (mongoc_client_t *client, const char *db_name, const char *${groupField}, int64_t measured_at_ms, const bson_t *measurement, bson_error_t *error)
{
   const int64_t window_ms = (int64_t) ${spec.bucket.windowMinutes} * 60000LL;
   const int64_t window_start_ms = (measured_at_ms / window_ms) * window_ms;
   char bucket_id[512];
   time_t window_secs = (time_t) (window_start_ms / 1000LL);
   struct tm window_tm;
   gmtime_r (&window_secs, &window_tm);
   char iso_buf[64];
   strftime (iso_buf, sizeof (iso_buf), "%Y-%m-%dT%H:%M:%SZ", &window_tm);
   snprintf (bucket_id, sizeof (bucket_id), "%s|%s", ${groupField}, iso_buf);

   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "_id", bucket_id);

   bson_t set_on_insert = BSON_INITIALIZER;
   BSON_APPEND_INT32 (&set_on_insert, "schemaVersion", 1);
   BSON_APPEND_UTF8 (&set_on_insert, "${groupField}", ${groupField});
   BSON_APPEND_DATE_TIME (&set_on_insert, "windowStart", window_start_ms);
   BSON_APPEND_INT32 (&set_on_insert, "windowMinutes", ${spec.bucket.windowMinutes});

   bson_t update = BSON_INITIALIZER;
   {
      bson_t push_doc = BSON_INITIALIZER;
      BSON_APPEND_DOCUMENT (&push_doc, "${spec.bucket.measurementsField}", measurement);
      BSON_APPEND_DOCUMENT (&update, "$push", &push_doc);
      bson_destroy (&push_doc);
   }
   {
      bson_t inc_doc = BSON_INITIALIZER;
      BSON_APPEND_INT32 (&inc_doc, "count", 1);
      BSON_APPEND_DOCUMENT (&update, "$inc", &inc_doc);
      bson_destroy (&inc_doc);
   }
   BSON_APPEND_DOCUMENT (&update, "$setOnInsert", &set_on_insert);

   bson_t opts = BSON_INITIALIZER;
   BSON_APPEND_BOOL (&opts, "upsert", true);
   bool ok = mongoc_collection_update_one (collection, &filter, &update, &opts, NULL, error);
   bson_destroy (&filter);
   bson_destroy (&set_on_insert);
   bson_destroy (&update);
   bson_destroy (&opts);
   mongoc_collection_destroy (collection);
   return ok;
}
`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    parts.push(`
bool
${spec.camelName}_fan_out_${reference.field}_update (mongoc_client_t *client, const char *db_name, const char *${viaField}, const bson_t *fields, bson_error_t *error)
{
   mongoc_collection_t *collection = ${spec.camelName}_collection (client, db_name);
   bson_t filter = BSON_INITIALIZER;
   BSON_APPEND_UTF8 (&filter, "${viaField}", ${viaField});

   bson_t set_doc = BSON_INITIALIZER;
   bson_iter_t iter;
   if (bson_iter_init (&iter, fields)) {
      while (bson_iter_next (&iter)) {
         const char *key = bson_iter_key (&iter);
         char dotted[512];
         snprintf (dotted, sizeof (dotted), "${reference.field}.%s", key);
         if (BSON_ITER_HOLDS_UTF8 (&iter)) {
            BSON_APPEND_UTF8 (&set_doc, dotted, bson_iter_utf8 (&iter, NULL));
         } else if (BSON_ITER_HOLDS_INT32 (&iter)) {
            BSON_APPEND_INT32 (&set_doc, dotted, bson_iter_int32 (&iter));
         } else if (BSON_ITER_HOLDS_INT64 (&iter)) {
            BSON_APPEND_INT64 (&set_doc, dotted, bson_iter_int64 (&iter));
         } else if (BSON_ITER_HOLDS_DOUBLE (&iter)) {
            BSON_APPEND_DOUBLE (&set_doc, dotted, bson_iter_double (&iter));
         } else if (BSON_ITER_HOLDS_BOOL (&iter)) {
            BSON_APPEND_BOOL (&set_doc, dotted, bson_iter_bool (&iter));
         } else if (BSON_ITER_HOLDS_DATE_TIME (&iter)) {
            BSON_APPEND_DATE_TIME (&set_doc, dotted, bson_iter_date_time (&iter));
         } else if (BSON_ITER_HOLDS_DOCUMENT (&iter)) {
            const uint8_t *child = NULL;
            uint32_t child_len = 0;
            bson_iter_document (&iter, &child_len, &child);
            bson_t child_doc;
            bson_init_static (&child_doc, child, child_len);
            BSON_APPEND_DOCUMENT (&set_doc, dotted, &child_doc);
         }
      }
   }

   bson_t update = BSON_INITIALIZER;
   BSON_APPEND_DOCUMENT (&update, "$set", &set_doc);
   bool ok = mongoc_collection_update_many (collection, &filter, &update, NULL, NULL, error);
   bson_destroy (&filter);
   bson_destroy (&set_doc);
   bson_destroy (&update);
   mongoc_collection_destroy (collection);
   return ok;
}
`);
  }

  parts.push('');
  return parts.join('\n');
}

export const cLanguage: RepogenLanguage = {
  id: 'c',
  label: 'C',
  driverName: 'libmongoc',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.h', content: renderClient(plan) },
      { relativePath: 'mongo_client.c', content: renderClientSource(plan) },
      { relativePath: 'ensure_indexes.h', content: renderIndexesHeader() },
      { relativePath: 'ensure_indexes.c', content: renderIndexesSource(plan) },
      ...specs.flatMap((spec) => [
        { relativePath: `${spec.name}_repository.h`, content: renderRepositoryHeader(spec) },
        { relativePath: `${spec.name}_repository.c`, content: renderRepositorySource(spec) },
      ]),
    ];
  },
};
