import type { MigrationPlan } from '../../types.js';
import { toCamelCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToCpp } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `/*
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
 */
`;

function renderIndexKvps(keys: Record<string, number>): string {
  return Object.entries(keys)
    .map(([key, direction]) => `kvp("${key}", ${direction})`)
    .join(', ');
}

function renderClientHeader(): string {
  return `${HEADER}
#pragma once

#include <mongocxx/client.hpp>
#include <mongocxx/database.hpp>
#include <string>

namespace hvymetl {

mongocxx::database get_database(const std::string& uri, const std::string& db_name);
void close_database();

}  // namespace hvymetl
`;
}

function renderClientSource(plan: MigrationPlan): string {
  return `${HEADER}
#include "mongo_client.hpp"

#include <mongocxx/instance.hpp>
#include <mongocxx/pool.hpp>
#include <mongocxx/uri.hpp>
#include <optional>

namespace hvymetl {

namespace {
mongocxx::instance g_instance{};
std::optional<mongocxx::pool> g_pool;
}  // namespace

mongocxx::database get_database(const std::string& uri, const std::string& db_name)
{
   if (!g_pool) {
      mongocxx::uri mongo_uri{uri};
      mongocxx::options::pool pool_opts;
      pool_opts.max_pool_size(${plan.pool.maxPoolSize});
      pool_opts.min_pool_size(${plan.pool.minPoolSize});
      g_pool.emplace(mongo_uri, pool_opts);
   }
   auto client = g_pool->acquire();
   return (*client)[db_name];
}

void close_database()
{
   g_pool.reset();
}

}  // namespace hvymetl
`;
}

function renderIndexesHeader(): string {
  return `${HEADER}
#pragma once

#include <mongocxx/client.hpp>
#include <string>

namespace hvymetl {

void ensure_indexes(mongocxx::database db);

}  // namespace hvymetl
`;
}

function renderIndexesSource(plan: MigrationPlan): string {
  const lines = [
    `${HEADER}
#include "ensure_indexes.hpp"

#include <bsoncxx/builder/basic/document.hpp>
#include <mongocxx/options/index.hpp>

namespace bbasic = bsoncxx::builder::basic;
using bbasic::kvp;
using bbasic::make_document;

namespace hvymetl {

void ensure_indexes(mongocxx::database db)
{`,
  ];

  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`   // ${index.reason}`);
      const unique = index.options.unique ? '.unique(true)' : '';
      lines.push(`   {`);
      lines.push(`      auto coll = db["${collection.name}"];`);
      lines.push(
        `      coll.create_index(make_document(${renderIndexKvps(index.keys)}), mongocxx::options::index().name("${index.options.name}")${unique});`,
      );
      lines.push(`   }`);
    }
  }

  lines.push(`}`);
  lines.push('');
  lines.push(`}  // namespace hvymetl`);
  lines.push('');
  return lines.join('\n');
}

function renderRepositoryHeader(spec: CollectionCodegenSpec): string {
  const fieldComments = spec.fields
    .map((field) => ` *   ${field.name}: ${bsonToCpp(field.bsonType)}`)
    .join('\n');

  const decls: string[] = [
    `mongocxx::collection ${spec.camelName}_collection(mongocxx::database db);`,
    `std::optional<bsoncxx::document::value> ${spec.camelName}_find_by_id(mongocxx::database db, const std::string& id);`,
    `std::vector<bsoncxx::document::value> ${spec.camelName}_list(mongocxx::database db, const std::optional<std::string>& after_id, int page_size);`,
    `void ${spec.camelName}_insert(mongocxx::database db, bsoncxx::document::view document);`,
    `void ${spec.camelName}_update_fields(mongocxx::database db, const std::string& id, bsoncxx::document::view fields);`,
  ];

  for (const computed of spec.computedFields) {
    decls.push(
      `void ${spec.camelName}_increment_${computed.field}(mongocxx::database db, const std::string& id, int64_t delta = 1);`,
    );
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    decls.push(
      `void ${spec.camelName}_push_to_${arrayPlan.field}(mongocxx::database db, const std::string& id, bsoncxx::document::view item);`,
    );
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    decls.push(
      `void ${spec.camelName}_record_measurement(mongocxx::database db, const std::string& ${groupField}, int64_t measured_at_ms, bsoncxx::document::view measurement);`,
    );
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    decls.push(
      `void ${spec.camelName}_fan_out_${reference.field}_update(mongocxx::database db, const ${bsonToCpp(spec.fields.find((f) => f.name === viaField)?.bsonType)}& ${viaField}, bsoncxx::document::view fields);`,
    );
  }

  return `${HEADER}
#pragma once

#include <bsoncxx/document/value.hpp>
#include <mongocxx/collection.hpp>
#include <mongocxx/database.hpp>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace hvymetl {

/*
 * Repository for "${spec.name}" (source table: ${spec.sourceTable}).
 * Document fields:
${fieldComments}
 */

${decls.join('\n')}

}  // namespace hvymetl
`;
}

function renderRepositorySource(spec: CollectionCodegenSpec): string {
  const parts: string[] = [
    `${HEADER}
#include "${spec.name}_repository.hpp"

#include <bsoncxx/builder/basic/array.hpp>
#include <bsoncxx/builder/basic/document.hpp>
#include <bsoncxx/json.hpp>
#include <chrono>
#include <iomanip>
#include <mongocxx/options/find.hpp>
#include <mongocxx/options/update.hpp>
#include <sstream>

namespace bbasic = bsoncxx::builder::basic;
using bbasic::kvp;
using bbasic::make_array;
using bbasic::make_document;

namespace hvymetl {

mongocxx::collection ${spec.camelName}_collection(mongocxx::database db)
{
   return db["${spec.name}"];
}

std::optional<bsoncxx::document::value> ${spec.camelName}_find_by_id(mongocxx::database db, const std::string& id)
{
   auto coll = ${spec.camelName}_collection(db);
   auto result = coll.find_one(make_document(kvp("_id", id)));
   if (result) {
      return std::optional<bsoncxx::document::value>{std::move(*result)};
   }
   return std::nullopt;
}

std::vector<bsoncxx::document::value> ${spec.camelName}_list(
   mongocxx::database db,
   const std::optional<std::string>& after_id,
   int page_size)
{
   auto coll = ${spec.camelName}_collection(db);
   bsoncxx::document::value filter = after_id
      ? make_document(kvp("_id", make_document(kvp("$gt", *after_id))))
      : make_document();
   mongocxx::options::find opts;
   opts.sort(make_document(kvp("_id", 1))).limit(page_size);
   std::vector<bsoncxx::document::value> docs;
   for (auto&& doc : coll.find(filter.view(), opts)) {
      docs.emplace_back(doc);
   }
   return docs;
}

void ${spec.camelName}_insert(mongocxx::database db, bsoncxx::document::view document)
{
   bbasic::document builder;
   for (auto&& element : document) {
      builder.append(kvp(element.key(), element.get_value()));
   }
   builder.append(kvp("schemaVersion", 1));
   ${spec.camelName}_collection(db).insert_one(builder.view());
}

void ${spec.camelName}_update_fields(mongocxx::database db, const std::string& id, bsoncxx::document::view fields)
{
   ${spec.camelName}_collection(db).update_one(
      make_document(kvp("_id", id)),
      make_document(kvp("$set", fields)));
}
`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
void ${spec.camelName}_increment_${computed.field}(mongocxx::database db, const std::string& id, int64_t delta)
{
   ${spec.camelName}_collection(db).update_one(
      make_document(kvp("_id", id)),
      make_document(kvp("$inc", make_document(kvp("${computed.field}", delta)))));
}
`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
void ${spec.camelName}_push_to_${arrayPlan.field}(mongocxx::database db, const std::string& id, bsoncxx::document::view item)
{
   ${spec.camelName}_collection(db).update_one(
      make_document(kvp("_id", id)),
      make_document(kvp("$push", make_document(kvp("${arrayPlan.field}", make_document(
         kvp("$each", make_array(item)),
         kvp("$position", 0),
         kvp("$slice", ${arrayPlan.subsetLimit})))))));
}
`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
void ${spec.camelName}_record_measurement(
   mongocxx::database db,
   const std::string& ${groupField},
   int64_t measured_at_ms,
   bsoncxx::document::view measurement)
{
   const int64_t window_ms = static_cast<int64_t>(${spec.bucket.windowMinutes}) * 60000LL;
   const int64_t window_start_ms = (measured_at_ms / window_ms) * window_ms;
   const auto window_start = std::chrono::system_clock::time_point{std::chrono::milliseconds{window_start_ms}};
   const auto time_t_value = std::chrono::system_clock::to_time_t(window_start);
   std::tm utc_tm{};
   gmtime_r(&time_t_value, &utc_tm);
   std::ostringstream iso;
   iso << std::put_time(&utc_tm, "%Y-%m-%dT%H:%M:%SZ");
   const std::string bucket_id = ${groupField} + "|" + iso.str();

   ${spec.camelName}_collection(db).update_one(
      make_document(kvp("_id", bucket_id)),
      make_document(
         kvp("$push", make_document(kvp("${spec.bucket.measurementsField}", measurement))),
         kvp("$inc", make_document(kvp("count", 1))),
         kvp("$setOnInsert", make_document(
            kvp("schemaVersion", 1),
            kvp("${groupField}", ${groupField}),
            kvp("windowStart", bsoncxx::types::b_date{std::chrono::milliseconds{window_start_ms}}),
            kvp("windowMinutes", ${spec.bucket.windowMinutes})))),
      mongocxx::options::update().upsert(true));
}
`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    parts.push(`
void ${spec.camelName}_fan_out_${reference.field}_update(
   mongocxx::database db,
   const ${bsonToCpp(spec.fields.find((f) => f.name === viaField)?.bsonType)}& ${viaField},
   bsoncxx::document::view fields)
{
   bbasic::document dotted;
   for (auto&& element : fields) {
      const std::string key = element.key().to_string();
      dotted.append(kvp("${reference.field}." + key, element.get_value()));
   }
   ${spec.camelName}_collection(db).update_many(
      make_document(kvp("${viaField}", ${viaField})),
      make_document(kvp("$set", dotted.view())));
}
`);
  }

  parts.push(`}  // namespace hvymetl`);
  parts.push('');
  return parts.join('\n');
}

export const cppLanguage: RepogenLanguage = {
  id: 'cpp',
  label: 'C++',
  driverName: 'mongocxx',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.hpp', content: renderClientHeader() },
      { relativePath: 'mongo_client.cpp', content: renderClientSource(plan) },
      { relativePath: 'ensure_indexes.hpp', content: renderIndexesHeader() },
      { relativePath: 'ensure_indexes.cpp', content: renderIndexesSource(plan) },
      ...specs.flatMap((spec) => [
        { relativePath: `${spec.name}_repository.hpp`, content: renderRepositoryHeader(spec) },
        { relativePath: `${spec.name}_repository.cpp`, content: renderRepositorySource(spec) },
      ]),
    ];
  },
};
