import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToCSharp } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `// Generated by hvymetl repogen. Regenerate from migration-plan.json.
// SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
`;

function csharpPropertyName(fieldName: string): string {
  if (fieldName === '_id') return 'Id';
  return toPascalCase(fieldName);
}

function csharpPropertyType(bsonType: string | string[] | undefined, optional: boolean): string {
  const base = bsonToCSharp(bsonType);
  if (!optional) return base;
  if (base.endsWith('?')) return base;
  if (base === 'string') return 'string?';
  if (base === 'bool') return 'bool?';
  if (base === 'long') return 'long?';
  if (base === 'double') return 'double?';
  if (base === 'DateTime') return 'DateTime?';
  if (base === 'BsonDocument') return 'BsonDocument?';
  if (base === 'List<BsonDocument>') return 'List<BsonDocument>?';
  return 'object?';
}

function renderWriteConcern(plan: MigrationPlan): string {
  const w =
    plan.writeConcern.w === 'majority'
      ? 'WriteConcern.WMajority'
      : `WriteConcern.W(${plan.writeConcern.w})`;
  return `${w}.WithJournal(${plan.writeConcern.journal})`;
}

function renderIndexKeys(keys: Record<string, number>): string {
  const parts = Object.entries(keys).map(
    ([field, direction]) =>
      direction >= 0
        ? `.Ascending("${field}")`
        : `.Descending("${field}")`,
  );
  return `Builders<BsonDocument>.IndexKeys${parts.join('')}`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
using MongoDB.Bson;
using MongoDB.Driver;

namespace Hvymetl.Repositories;

public static class MongoClientFactory
{
    private static MongoClient? _client;

    public static IMongoDatabase GetDb(string uri, string dbName)
    {
        if (_client is null)
        {
            var settings = MongoClientSettings.FromConnectionString(uri);
            settings.MaxConnectionPoolSize = ${plan.pool.maxPoolSize};
            settings.MinConnectionPoolSize = ${plan.pool.minPoolSize};
            settings.SocketTimeout = TimeSpan.FromMilliseconds(${plan.pool.socketTimeoutMS});
            settings.MaxConnectionIdleTime = TimeSpan.FromMilliseconds(${plan.pool.maxIdleTimeMS});
            settings.WriteConcern = ${renderWriteConcern(plan)};
            _client = new MongoClient(settings);
        }
        return _client.GetDatabase(dbName);
    }

    public static void CloseDb()
    {
        _client?.Dispose();
        _client = null;
    }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'using MongoDB.Bson;',
    'using MongoDB.Driver;',
    '',
    'namespace Hvymetl.Repositories;',
    '',
    'public static class EnsureIndexes',
    '{',
    '    public static async Task RunAsync(IMongoDatabase db, CancellationToken cancellationToken = default)',
    '    {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        // ${index.reason}`);
      const unique = index.options.unique ? '\n                Unique = true,' : '';
      lines.push(`        await db.GetCollection<BsonDocument>("${collection.name}")`);
      lines.push('            .Indexes.CreateOneAsync(');
      lines.push('                new CreateIndexModel<BsonDocument>(');
      lines.push(`                    ${renderIndexKeys(index.keys)},`);
      lines.push('                    new CreateIndexOptions');
      lines.push('                    {');
      lines.push(`                        Name = "${index.options.name}",${unique}`);
      lines.push('                    }),');
      lines.push('                cancellationToken: cancellationToken);');
    }
  }
  lines.push('    }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const structFields = spec.fields
    .map((field) => {
      const propName = csharpPropertyName(field.name);
      const propType = csharpPropertyType(field.bsonType, field.optional);
      const element = field.name === '_id' ? '[BsonId]\n    [BsonRepresentation(BsonType.String)]' : `[BsonElement("${field.name}")]`;
      return `    ${element}\n    public ${propType} ${propName} { get; set; }${field.name === '_id' ? ' = "";' : field.optional ? '' : ''}`;
    })
    .join('\n\n');

  const parts: string[] = [
    `${HEADER}
using MongoDB.Bson;
using MongoDB.Driver;

namespace Hvymetl.Repositories;

/// <summary>Repository for "${spec.name}" (source table: ${spec.sourceTable}).</summary>
public static class ${spec.pascalName}Repository
{
    private static IMongoCollection<${spec.pascalName}Document> Collection(IMongoDatabase db) =>
        db.GetCollection<${spec.pascalName}Document>("${spec.name}");

    public static async Task<${spec.pascalName}Document?> FindByIdAsync(
        IMongoDatabase db,
        string id,
        CancellationToken cancellationToken = default)
    {
        return await Collection(db)
            .Find(Builders<${spec.pascalName}Document>.Filter.Eq(d => d.Id, id))
            .FirstOrDefaultAsync(cancellationToken);
    }

    public static async Task<List<${spec.pascalName}Document>> ListAsync(
        IMongoDatabase db,
        string? afterId,
        int pageSize,
        CancellationToken cancellationToken = default)
    {
        var filter = afterId is null
            ? Builders<${spec.pascalName}Document>.Filter.Empty
            : Builders<${spec.pascalName}Document>.Filter.Gt(d => d.Id, afterId);
        return await Collection(db)
            .Find(filter)
            .Sort(Builders<${spec.pascalName}Document>.Sort.Ascending(d => d.Id))
            .Limit(pageSize)
            .ToListAsync(cancellationToken);
    }

    public static async Task InsertAsync(
        IMongoDatabase db,
        ${spec.pascalName}Document document,
        CancellationToken cancellationToken = default)
    {
        var payload = document.ToBsonDocument();
        payload["schemaVersion"] = 1;
        await Collection(db).InsertOneAsync(payload, cancellationToken: cancellationToken);
    }

    public static async Task UpdateFieldsAsync(
        IMongoDatabase db,
        string id,
        BsonDocument fields,
        CancellationToken cancellationToken = default)
    {
        await Collection(db).UpdateOneAsync(
            Builders<${spec.pascalName}Document>.Filter.Eq(d => d.Id, id),
            new BsonDocument("$set", fields),
            cancellationToken: cancellationToken);
    }`,
  ];

  for (const computed of spec.computedFields) {
    const fn = toPascalCase(computed.field);
    parts.push(`
    public static async Task Increment${fn}Async(
        IMongoDatabase db,
        string id,
        long delta = 1,
        CancellationToken cancellationToken = default)
    {
        await Collection(db).UpdateOneAsync(
            Builders<${spec.pascalName}Document>.Filter.Eq(d => d.Id, id),
            Builders<BsonDocument>.Update.Inc("${computed.field}", delta),
            cancellationToken: cancellationToken);
    }`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
    public static async Task PushTo${toPascalCase(arrayPlan.field)}Async(
        IMongoDatabase db,
        string id,
        BsonDocument item,
        CancellationToken cancellationToken = default)
    {
        await Collection(db).UpdateOneAsync(
            Builders<${spec.pascalName}Document>.Filter.Eq(d => d.Id, id),
            Builders<BsonDocument>.Update.PushEach(
                "${arrayPlan.field}",
                new[] { item },
                position: 0,
                slice: ${arrayPlan.subsetLimit}),
            cancellationToken: cancellationToken);
    }`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
    public static async Task RecordMeasurementAsync(
        IMongoDatabase db,
        string ${groupField},
        DateTime measuredAt,
        BsonDocument measurement,
        CancellationToken cancellationToken = default)
    {
        var windowMs = TimeSpan.FromMinutes(${spec.bucket.windowMinutes});
        var windowStart = new DateTime(
            measuredAt.Ticks - (measuredAt.Ticks % windowMs.Ticks),
            measuredAt.Kind);
        var bucketId = $"{${groupField}}|{windowStart.ToUniversalTime():yyyy-MM-ddTHH:mm:ssZ}";
        await Collection(db).UpdateOneAsync(
            Builders<${spec.pascalName}Document>.Filter.Eq(d => d.Id, bucketId),
            Builders<BsonDocument>.Update
                .Push("${spec.bucket.measurementsField}", measurement)
                .Inc("count", 1)
                .SetOnInsert(new BsonDocument
                {
                    { "schemaVersion", 1 },
                    { "${groupField}", ${groupField} },
                    { "windowStart", windowStart },
                    { "windowMinutes", ${spec.bucket.windowMinutes} },
                }),
            new UpdateOptions { IsUpsert = true },
            cancellationToken);
    }`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = csharpPropertyType(
      spec.fields.find((field) => field.name === viaField)?.bsonType,
      false,
    );
    parts.push(`
    public static async Task FanOut${toPascalCase(reference.field)}UpdateAsync(
        IMongoDatabase db,
        ${viaType} ${viaField},
        BsonDocument fields,
        CancellationToken cancellationToken = default)
    {
        var updates = fields.Elements
            .Select(element => Builders<BsonDocument>.Update.Set(
                $"{reference.field}.{element.Name}",
                element.Value))
            .ToList();
        if (updates.Count == 0) return;
        await Collection(db).UpdateManyAsync(
            Builders<BsonDocument>.Filter.Eq("${viaField}", ${viaField}),
            Builders<BsonDocument>.Update.Combine(updates),
            cancellationToken: cancellationToken);
    }`);
  }

  parts.push(`
}

public class ${spec.pascalName}Document
{
${structFields}
}
`);

  return parts.join('\n');
}

export const csharpLanguage: RepogenLanguage = {
  id: 'csharp',
  label: 'C#',
  driverName: 'MongoDB.Driver',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'MongoClient.cs', content: renderClient(plan) },
      { relativePath: 'EnsureIndexes.cs', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.pascalName}Repository.cs`,
        content: renderRepository(spec),
      })),
    ];
  },
};
