import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToGo } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `// Generated by hvymetl repogen. Regenerate from migration-plan.json.
// SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
`;

function goFieldName(fieldName: string): string {
  if (fieldName === '_id') return 'ID';
  return toPascalCase(fieldName);
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
package repositories

import (
	"context"
	"sync"
	"time"

	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

var (
	clientOnce sync.Once
	client     *mongo.Client
	clientErr  error
)

func GetDB(ctx context.Context, uri, dbName string) (*mongo.Database, error) {
	clientOnce.Do(func() {
		opts := options.Client().
			ApplyURI(uri).
			SetMaxPoolSize(${plan.pool.maxPoolSize}).
			SetMinPoolSize(${plan.pool.minPoolSize}).
			SetSocketTimeout(${plan.pool.socketTimeoutMS} * time.Millisecond).
			SetMaxConnIdleTime(${plan.pool.maxIdleTimeMS} * time.Millisecond)
		client, clientErr = mongo.Connect(ctx, opts)
	})
	if clientErr != nil {
		return nil, clientErr
	}
	return client.Database(dbName), nil
}

func CloseDB(ctx context.Context) error {
	if client == nil {
		return nil
	}
	return client.Disconnect(ctx)
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'package repositories',
    '',
    'import (',
    '\t"context"',
    '',
    '\t"go.mongodb.org/mongo-driver/bson"',
    '\t"go.mongodb.org/mongo-driver/mongo"',
    '\t"go.mongodb.org/mongo-driver/mongo/options"',
    ')',
    '',
    'func EnsureIndexes(ctx context.Context, db *mongo.Database) error {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`\t// ${index.reason}`);
      const keyDoc = Object.entries(index.keys)
        .map(([k, v]) => `bson.E{Key: "${k}", Value: ${v}}`)
        .join(', ');
      const unique = index.options.unique ? '.SetUnique(true)' : '';
      lines.push(
        `\tif _, err := db.Collection("${collection.name}").Indexes().CreateOne(ctx, mongo.IndexModel{Keys: bson.D{${keyDoc}}, Options: options.Index().SetName("${index.options.name}")${unique}}); err != nil {`,
      );
      lines.push('\t\treturn err');
      lines.push('\t}');
    }
  }
  lines.push('\treturn nil');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const structFields = spec.fields
    .map((field) => `\t${goFieldName(field.name)} ${bsonToGo(field.bsonType)} \`bson:"${field.name}${field.optional ? ',omitempty' : ''}"\``)
    .join('\n');

  const parts: string[] = [
    `${HEADER}
package repositories

import (
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type ${spec.pascalName}Document struct {
${structFields}
}

func ${spec.pascalName}Collection(db *mongo.Database) *mongo.Collection {
	return db.Collection("${spec.name}")
}

func Find${spec.pascalName}ByID(ctx context.Context, db *mongo.Database, id string) (*${spec.pascalName}Document, error) {
	var doc ${spec.pascalName}Document
	err := ${spec.pascalName}Collection(db).FindOne(ctx, bson.M{"_id": id}).Decode(&doc)
	if err == mongo.ErrNoDocuments {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("find ${spec.name}: %w", err)
	}
	return &doc, nil
}

func Insert${spec.pascalName}(ctx context.Context, db *mongo.Database, doc bson.M) error {
	doc["schemaVersion"] = 1
	_, err := ${spec.pascalName}Collection(db).InsertOne(ctx, doc)
	return err
}

func Update${spec.pascalName}Fields(ctx context.Context, db *mongo.Database, id string, fields bson.M) error {
	_, err := ${spec.pascalName}Collection(db).UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$set": fields})
	return err
}`,
  ];

  for (const computed of spec.computedFields) {
    const fn = toPascalCase(computed.field);
    parts.push(`
func Increment${fn}(ctx context.Context, db *mongo.Database, id string, delta int64) error {
	_, err := ${spec.pascalName}Collection(db).UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$inc": bson.M{"${computed.field}": delta}})
	return err
}`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
func PushTo${toPascalCase(arrayPlan.field)}(ctx context.Context, db *mongo.Database, id string, item bson.M) error {
	update := bson.M{"$push": bson.M{"${arrayPlan.field}": bson.M{"$each": bson.A{item}, "$position": 0, "$slice": ${arrayPlan.subsetLimit}}}}
	_, err := ${spec.pascalName}Collection(db).UpdateOne(ctx, bson.M{"_id": id}, update)
	return err
}`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
func Record${spec.pascalName}Measurement(ctx context.Context, db *mongo.Database, ${groupField} string, measuredAt time.Time, measurement bson.M) error {
	windowMs := time.Duration(${spec.bucket.windowMinutes}) * time.Minute
	windowStart := measuredAt.Truncate(windowMs)
	bucketID := fmt.Sprintf("%s|%s", ${groupField}, windowStart.UTC().Format(time.RFC3339))
	upsert := true
	_, err := ${spec.pascalName}Collection(db).UpdateOne(ctx, bson.M{"_id": bucketID}, bson.M{
		"$push": bson.M{"${spec.bucket.measurementsField}": measurement},
		"$inc":  bson.M{"count": 1},
		"$setOnInsert": bson.M{
			"schemaVersion": 1,
			"${groupField}": ${groupField},
			"windowStart":   windowStart,
			"windowMinutes": ${spec.bucket.windowMinutes},
		},
	}, &options.UpdateOptions{Upsert: &upsert})
	return err
}`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    parts.push(`
func FanOut${toPascalCase(reference.field)}Update(ctx context.Context, db *mongo.Database, ${viaField} interface{}, fields bson.M) error {
	dotted := bson.M{}
	for key, value := range fields {
		dotted["${reference.field}."+key] = value
	}
	_, err := ${spec.pascalName}Collection(db).UpdateMany(ctx, bson.M{"${viaField}": ${viaField}}, bson.M{"$set": dotted})
	return err
}`);
  }

  parts.push('');
  return parts.join('\n');
}

export const goLanguage: RepogenLanguage = {
  id: 'go',
  label: 'Go',
  driverName: 'mongo-go-driver',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.go', content: renderClient(plan) },
      { relativePath: 'ensure_indexes.go', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.name}_repository.go`,
        content: renderRepository(spec),
      })),
    ];
  },
};
