import type { MigrationPlan } from '../../types.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToJava } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';

const HEADER = `/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · strict typing · atomic MongoDB modifiers only · no read-modify-write loops.
 */`;

function renderWriteConcern(plan: MigrationPlan): string {
  const w = plan.writeConcern.w;
  const journal = plan.writeConcern.journal;
  const base =
    w === 'majority'
      ? 'WriteConcern.MAJORITY'
      : typeof w === 'number'
        ? `new WriteConcern(${w})`
        : 'WriteConcern.ACKNOWLEDGED';
  return journal ? `${base}.withJournal(true)` : base;
}

function renderIndexKeys(keys: Record<string, number>): string {
  const entries = Object.entries(keys);
  if (entries.length === 0) return 'new Document()';
  const [first, ...rest] = entries;
  let doc = `new Document("${first[0]}", ${first[1]})`;
  for (const [key, value] of rest) {
    doc += `.append("${key}", ${value})`;
  }
  return doc;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}

package repositories;

import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.WriteConcern;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;

import java.util.concurrent.TimeUnit;

public final class MongoClientFactory {
    private static MongoClient client;

    private MongoClientFactory() {}

    public static MongoDatabase getDb(String uri, String dbName) {
        if (client == null) {
            MongoClientSettings settings = MongoClientSettings.builder()
                .applyConnectionString(new ConnectionString(uri))
                .applyToConnectionPoolSettings(builder -> builder
                    .maxSize(${plan.pool.maxPoolSize})
                    .minSize(${plan.pool.minPoolSize})
                    .maxConnectionIdleTime(${plan.pool.maxIdleTimeMS}, TimeUnit.MILLISECONDS))
                .applyToSocketSettings(builder -> builder
                    .connectTimeout(${plan.pool.socketTimeoutMS}, TimeUnit.MILLISECONDS))
                .writeConcern(${renderWriteConcern(plan)})
                .build();
            client = MongoClients.create(settings);
        }
        return client.getDatabase(dbName);
    }

    public static void close() {
        if (client != null) {
            client.close();
            client = null;
        }
    }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    '',
    'package repositories;',
    '',
    'import com.mongodb.client.MongoDatabase;',
    'import com.mongodb.client.model.IndexOptions;',
    'import org.bson.Document;',
    '',
    'public final class EnsureIndexes {',
    '    private EnsureIndexes() {}',
    '',
    '    public static void ensure(MongoDatabase db) {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        // ${index.reason}`);
      const unique = index.options.unique ? '.unique(true)' : '';
      lines.push(
        `        db.getCollection("${collection.name}").createIndex(${renderIndexKeys(index.keys)}, new IndexOptions().name("${index.options.name}")${unique});`,
      );
    }
  }
  lines.push('    }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const typedFields = spec.fields
    .map((field) => ` *   ${field.name}: ${bsonToJava(field.bsonType)}${field.optional ? ' (optional)' : ''}`)
    .join('\n');

  const parts: string[] = [
    `${HEADER}
/**
 * Repository for "${spec.name}" (source table: ${spec.sourceTable}).
 * Document fields:
${typedFields}
 * Every write uses atomic server-side modifiers.
 */

package repositories;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Sorts;
import com.mongodb.client.model.UpdateOptions;
import org.bson.Document;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class ${spec.pascalName}Repository {
    private ${spec.pascalName}Repository() {}

    private static MongoCollection<Document> collection(MongoDatabase db) {
        return db.getCollection("${spec.name}");
    }

    public static Document findById(MongoDatabase db, String id) {
        return collection(db).find(Filters.eq("_id", id)).first();
    }

    public static List<Document> list(MongoDatabase db, String afterId, int pageSize) {
        Document filter = afterId != null ? new Document("_id", new Document("$gt", afterId)) : new Document();
        return collection(db).find(filter).sort(Sorts.ascending("_id")).limit(pageSize).into(new ArrayList<>());
    }

    public static void insert(MongoDatabase db, Document document) {
        document.put("schemaVersion", 1);
        collection(db).insertOne(document);
    }

    public static void updateFields(MongoDatabase db, String id, Document fields) {
        collection(db).updateOne(Filters.eq("_id", id), new Document("$set", fields));
    }`,
  ];

  for (const computed of spec.computedFields) {
    const fieldPascal = toPascalCase(computed.field);
    parts.push(`
    public static void increment${fieldPascal}(MongoDatabase db, String id) {
        increment${fieldPascal}(db, id, 1L);
    }

    public static void increment${fieldPascal}(MongoDatabase db, String id, long delta) {
        collection(db).updateOne(
            Filters.eq("_id", id),
            new Document("$inc", new Document("${computed.field}", delta)),
        );
    }`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const fieldPascal = toPascalCase(arrayPlan.field);
    parts.push(`
    public static void pushTo${fieldPascal}(MongoDatabase db, String id, Document item) {
        Document pushSpec = new Document("$each", Collections.singletonList(item))
            .append("$position", 0)
            .append("$slice", ${arrayPlan.subsetLimit});
        collection(db).updateOne(
            Filters.eq("_id", id),
            new Document("$push", new Document("${arrayPlan.field}", pushSpec)),
        );
    }`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
    public static void record${spec.pascalName}Measurement(
        MongoDatabase db,
        String ${groupField},
        Instant measuredAt,
        Document measurement,
    ) {
        long windowMs = ${spec.bucket.windowMinutes}L * 60000L;
        Instant windowStart = Instant.ofEpochMilli((measuredAt.toEpochMilli() / windowMs) * windowMs);
        String bucketId = ${groupField} + "|" + windowStart.toString().replaceAll("\\\\.\\\\d{3}Z$", "Z");
        Document update = new Document("$push", new Document("${spec.bucket.measurementsField}", measurement))
            .append("$inc", new Document("count", 1))
            .append("$setOnInsert", new Document()
                .append("schemaVersion", 1)
                .append("${groupField}", ${groupField})
                .append("windowStart", windowStart)
                .append("windowMinutes", ${spec.bucket.windowMinutes}));
        collection(db).updateOne(
            Filters.eq("_id", bucketId),
            update,
            new UpdateOptions().upsert(true),
        );
    }`);
  }

  for (const reference of spec.extendedReferences) {
    const fieldPascal = toPascalCase(reference.field);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToJava(spec.fields.find((f) => f.name === viaField)?.bsonType);
    parts.push(`
    public static void fanOut${fieldPascal}Update(MongoDatabase db, ${viaType} ${viaField}, Document fields) {
        Document dotted = new Document();
        for (Map.Entry<String, Object> entry : fields.entrySet()) {
            dotted.append("${reference.field}." + entry.getKey(), entry.getValue());
        }
        collection(db).updateMany(Filters.eq("${viaField}", ${viaField}), new Document("$set", dotted));
    }`);
  }

  parts.push('}');
  parts.push('');
  return parts.join('\n');
}

function generate(plan: MigrationPlan): GeneratedFile[] {
  const specs = buildCollectionSpecs(plan);
  return [
    { relativePath: 'MongoClientFactory.java', content: renderClient(plan) },
    { relativePath: 'EnsureIndexes.java', content: renderIndexes(plan) },
    ...specs.map((spec) => ({
      relativePath: `${spec.pascalName}Repository.java`,
      content: renderRepository(spec),
    })),
  ];
}

export const javaLanguage: RepogenLanguage = {
  id: 'java',
  label: 'Java',
  driverName: 'mongodb-driver-sync',
  generate,
};
