import type { MigrationPlan } from '../../types.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToKotlin } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';

const HEADER = `/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · strict typing · atomic MongoDB modifiers only · no read-modify-write loops.
 */`;

function renderWriteConcern(plan: MigrationPlan): string {
  const w = plan.writeConcern.w;
  const journal = plan.writeConcern.journal;
  const base =
    w === 'majority'
      ? 'WriteConcern.MAJORITY'
      : typeof w === 'number'
        ? `WriteConcern($w)`
        : 'WriteConcern.ACKNOWLEDGED';
  return journal ? `${base}.withJournal(true)` : base;
}

function renderIndexKeys(keys: Record<string, number>): string {
  const entries = Object.entries(keys);
  if (entries.length === 0) return 'Document()';
  const [first, ...rest] = entries;
  let doc = `Document("${first[0]}", ${first[1]})`;
  for (const [key, value] of rest) {
    doc += `.append("${key}", ${value})`;
  }
  return doc;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}

package repositories

import com.mongodb.ConnectionString
import com.mongodb.MongoClientSettings
import com.mongodb.WriteConcern
import com.mongodb.client.MongoClient
import com.mongodb.client.MongoClients
import com.mongodb.client.MongoDatabase
import java.util.concurrent.TimeUnit

object MongoClientFactory {
    private var client: MongoClient? = null

    fun getDb(uri: String, dbName: String): MongoDatabase {
        if (client == null) {
            val settings = MongoClientSettings.builder()
                .applyConnectionString(ConnectionString(uri))
                .applyToConnectionPoolSettings { builder ->
                    builder
                        .maxSize(${plan.pool.maxPoolSize})
                        .minSize(${plan.pool.minPoolSize})
                        .maxConnectionIdleTime(${plan.pool.maxIdleTimeMS}, TimeUnit.MILLISECONDS)
                }
                .applyToSocketSettings { builder ->
                    builder.connectTimeout(${plan.pool.socketTimeoutMS}, TimeUnit.MILLISECONDS)
                }
                .writeConcern(${renderWriteConcern(plan)})
                .build()
            client = MongoClients.create(settings)
        }
        return client!!.getDatabase(dbName)
    }

    fun close() {
        client?.close()
        client = null
    }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    '',
    'package repositories',
    '',
    'import com.mongodb.client.MongoDatabase',
    'import com.mongodb.client.model.IndexOptions',
    'import org.bson.Document',
    '',
    'object EnsureIndexes {',
    '    fun ensure(db: MongoDatabase) {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        // ${index.reason}`);
      const unique = index.options.unique ? '.unique(true)' : '';
      lines.push(
        `        db.getCollection("${collection.name}").createIndex(${renderIndexKeys(index.keys)}, IndexOptions().name("${index.options.name}")${unique})`,
      );
    }
  }
  lines.push('    }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const typedFields = spec.fields
    .map((field) => ` *   ${field.name}: ${bsonToKotlin(field.bsonType)}${field.optional ? ' (optional)' : ''}`)
    .join('\n');

  const parts: string[] = [
    `${HEADER}
/**
 * Repository for "${spec.name}" (source table: ${spec.sourceTable}).
 * Document fields:
${typedFields}
 * Every write uses atomic server-side modifiers.
 */

package repositories

import com.mongodb.client.MongoCollection
import com.mongodb.client.MongoDatabase
import com.mongodb.client.model.Filters
import com.mongodb.client.model.Sorts
import com.mongodb.client.model.UpdateOptions
import org.bson.Document
import java.time.Instant

object ${spec.pascalName}Repository {
    private fun collection(db: MongoDatabase): MongoCollection<Document> =
        db.getCollection("${spec.name}")

    fun findById(db: MongoDatabase, id: String): Document? =
        collection(db).find(Filters.eq("_id", id)).first()

    fun list(db: MongoDatabase, afterId: String?, pageSize: Int): List<Document> {
        val filter = if (afterId != null) Document("_id", Document("\$gt", afterId)) else Document()
        return collection(db).find(filter).sort(Sorts.ascending("_id")).limit(pageSize).toList()
    }

    fun insert(db: MongoDatabase, document: Document) {
        document["schemaVersion"] = 1
        collection(db).insertOne(document)
    }

    fun updateFields(db: MongoDatabase, id: String, fields: Document) {
        collection(db).updateOne(Filters.eq("_id", id), Document("\$set", fields))
    }`,
  ];

  for (const computed of spec.computedFields) {
    const fieldPascal = toPascalCase(computed.field);
    parts.push(`
    fun increment${fieldPascal}(db: MongoDatabase, id: String, delta: Long = 1L) {
        collection(db).updateOne(
            Filters.eq("_id", id),
            Document("\$inc", Document("${computed.field}", delta)),
        )
    }`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const fieldPascal = toPascalCase(arrayPlan.field);
    parts.push(`
    fun pushTo${fieldPascal}(db: MongoDatabase, id: String, item: Document) {
        val pushSpec = Document("\$each", listOf(item))
            .append("\$position", 0)
            .append("\$slice", ${arrayPlan.subsetLimit})
        collection(db).updateOne(
            Filters.eq("_id", id),
            Document("\$push", Document("${arrayPlan.field}", pushSpec)),
        )
    }`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
    fun record${spec.pascalName}Measurement(
        db: MongoDatabase,
        ${groupField}: String,
        measuredAt: Instant,
        measurement: Document,
    ) {
        val windowMs = ${spec.bucket.windowMinutes}L * 60000L
        val windowStart = Instant.ofEpochMilli((measuredAt.toEpochMilli() / windowMs) * windowMs)
        val bucketId = "\${${groupField}}|\${windowStart.toString().replace(Regex("\\\\.\\\\d{3}Z\$"), "Z")}"
        val update = Document("\$push", Document("${spec.bucket.measurementsField}", measurement))
            .append("\$inc", Document("count", 1))
            .append(
                "\$setOnInsert",
                Document()
                    .append("schemaVersion", 1)
                    .append("${groupField}", ${groupField})
                    .append("windowStart", windowStart)
                    .append("windowMinutes", ${spec.bucket.windowMinutes}),
            )
        collection(db).updateOne(
            Filters.eq("_id", bucketId),
            update,
            UpdateOptions().upsert(true),
        )
    }`);
  }

  for (const reference of spec.extendedReferences) {
    const fieldPascal = toPascalCase(reference.field);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToKotlin(spec.fields.find((f) => f.name === viaField)?.bsonType);
    parts.push(`
    fun fanOut${fieldPascal}Update(db: MongoDatabase, ${viaField}: ${viaType}, fields: Document) {
        val dotted = Document()
        for ((key, value) in fields) {
            dotted.append("${reference.field}.\$key", value)
        }
        collection(db).updateMany(Filters.eq("${viaField}", ${viaField}), Document("\$set", dotted))
    }`);
  }

  parts.push('}');
  parts.push('');
  return parts.join('\n');
}

function generate(plan: MigrationPlan): GeneratedFile[] {
  const specs = buildCollectionSpecs(plan);
  return [
    { relativePath: 'MongoClientFactory.kt', content: renderClient(plan) },
    { relativePath: 'EnsureIndexes.kt', content: renderIndexes(plan) },
    ...specs.map((spec) => ({
      relativePath: `${spec.pascalName}Repository.kt`,
      content: renderRepository(spec),
    })),
  ];
}

export const kotlinLanguage: RepogenLanguage = {
  id: 'kotlin',
  label: 'Kotlin',
  driverName: 'mongodb-driver-sync',
  generate,
};
