import type { MigrationPlan } from '../../types.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToTypeScript } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';
import { toCamelCase } from '../../utilities/naming.js';

const STANDARDS = `/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · strict typing · atomic MongoDB modifiers only · no read-modify-write loops.
 */`;

const READ_PREFERENCE_BY_SETTING: Record<string, string> = {
  primary: 'ReadPreference.primary',
  primaryPreferred: 'ReadPreference.primaryPreferred',
  secondary: 'ReadPreference.secondary',
  secondaryPreferred: 'ReadPreference.secondaryPreferred',
  nearest: 'ReadPreference.nearest',
};

function compressorsOption(compression: string): string {
  if (compression === 'none') return '';
  return `\n      compressors: ['${compression}'],`;
}

function renderClientModule(plan: MigrationPlan): string {
  const readPref = READ_PREFERENCE_BY_SETTING[plan.readPreference] ?? 'ReadPreference.primary';
  const compressors = compressorsOption(plan.compression);
  return `${STANDARDS}

import { MongoClient, type Db, ReadPreference } from 'mongodb';

let client: MongoClient | null = null;

export async function getDb(uri: string, dbName: string): Promise<Db> {
  if (!client) {
    client = new MongoClient(uri, {
      maxPoolSize: ${plan.pool.maxPoolSize},
      minPoolSize: ${plan.pool.minPoolSize},
      socketTimeoutMS: ${plan.pool.socketTimeoutMS},
      maxIdleTimeMS: ${plan.pool.maxIdleTimeMS},
      readPreference: ${readPref},${compressors}
      writeConcern: { w: ${JSON.stringify(plan.writeConcern.w)}, journal: ${plan.writeConcern.journal} },
    });
    await client.connect();
  }
  return client.db(dbName);
}

export async function closeDb(): Promise<void> {
  if (client) {
    await client.close();
    client = null;
  }
}
`;
}

function renderIndexModule(plan: MigrationPlan): string {
  const lines = [
    STANDARDS,
    '',
    "import { type Db } from 'mongodb';",
    '',
    'export async function ensureIndexes(db: Db): Promise<void> {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`  // ${index.reason}`);
      lines.push(
        `  await db.collection('${collection.name}').createIndex(${JSON.stringify(index.keys)}, { name: '${index.options.name}'${index.options.unique ? ', unique: true' : ''} });`,
      );
    }
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const { pascalName, name, sourceTable, fields } = spec;
  const typedFields = fields.map((field) => {
    const mark = field.optional ? '?' : '';
    return `  ${field.name}${mark}: ${bsonToTypeScript(field.bsonType)};`;
  });

  const parts: string[] = [
    `${STANDARDS}
/**
 * Repository for "${name}" (source table: ${sourceTable}).
 * Every write uses atomic server-side modifiers.
 */

import { type Collection, type Db, type Document } from 'mongodb';

export type ${pascalName}Document = {
${typedFields.join('\n')}
};

function collectionOf(db: Db): Collection<${pascalName}Document> {
  return db.collection<${pascalName}Document>('${name}');
}

export async function find${pascalName}ById(db: Db, id: string): Promise<${pascalName}Document | null> {
  return collectionOf(db).findOne({ _id: id });
}

export async function list${pascalName}(db: Db, afterId: string | null, pageSize: number): Promise<${pascalName}Document[]> {
  const filter = afterId ? { _id: { $gt: afterId } } : {};
  return collectionOf(db).find(filter).sort({ _id: 1 }).limit(pageSize).toArray();
}

export async function insert${pascalName}(db: Db, document: ${pascalName}Document): Promise<void> {
  await collectionOf(db).insertOne({ ...document, schemaVersion: 1 });
}

export async function update${pascalName}Fields(db: Db, id: string, fields: Partial<${pascalName}Document>): Promise<void> {
  await collectionOf(db).updateOne({ _id: id }, { $set: fields });
}`,
  ];

  for (const computed of spec.computedFields) {
    const fieldPascal = computed.field.charAt(0).toUpperCase() + computed.field.slice(1);
    parts.push(`
export async function increment${fieldPascal}(db: Db, id: string, delta = 1): Promise<void> {
  await collectionOf(db).updateOne({ _id: id }, { $inc: { ${computed.field}: delta } });
}`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const fieldPascal = arrayPlan.field.charAt(0).toUpperCase() + arrayPlan.field.slice(1);
    parts.push(`
export async function pushTo${fieldPascal}(db: Db, id: string, item: Document): Promise<void> {
  await collectionOf(db).updateOne(
    { _id: id },
    { $push: { ${arrayPlan.field}: { $each: [item], $position: 0, $slice: ${arrayPlan.subsetLimit} } } },
  );
}`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
export async function record${pascalName}Measurement(
  db: Db,
  ${groupField}: string,
  measuredAt: Date,
  measurement: Document,
): Promise<void> {
  const windowMs = ${spec.bucket.windowMinutes} * 60000;
  const windowStart = new Date(Math.floor(measuredAt.getTime() / windowMs) * windowMs);
  const bucketId = \`\${${groupField}}|\${windowStart.toISOString().replace(/\\.\\d{3}Z$/, 'Z')}\`;
  await collectionOf(db).updateOne(
    { _id: bucketId },
    {
      $push: { ${spec.bucket.measurementsField}: measurement },
      $inc: { count: 1 },
      $setOnInsert: {
        schemaVersion: 1,
        ${groupField}: ${groupField},
        windowStart,
        windowMinutes: ${spec.bucket.windowMinutes},
      },
    },
    { upsert: true },
  );
}`);
  }

  for (const reference of spec.extendedReferences) {
    const fieldPascal = reference.field.charAt(0).toUpperCase() + reference.field.slice(1);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToTypeScript(fields.find((f) => f.name === viaField)?.bsonType);
    parts.push(`
export async function fanOut${fieldPascal}Update(db: Db, ${viaField}: ${viaType}, fields: Document): Promise<void> {
  const dotted: Document = {};
  for (const [key, value] of Object.entries(fields)) dotted[\`${reference.field}.\${key}\`] = value;
  await collectionOf(db).updateMany({ ${viaField}: ${viaField} }, { $set: dotted });
}`);
  }

  parts.push('');
  return parts.join('\n');
}

function generate(plan: MigrationPlan): GeneratedFile[] {
  const specs = buildCollectionSpecs(plan);
  const files: GeneratedFile[] = [
    { relativePath: 'mongoClient.ts', content: renderClientModule(plan) },
    { relativePath: 'ensureIndexes.ts', content: renderIndexModule(plan) },
    ...specs.map((spec) => ({
      relativePath: `${spec.name}Repository.ts`,
      content: renderRepository(spec),
    })),
  ];
  return files;
}

export const nodeLanguage: RepogenLanguage = {
  id: 'node',
  label: 'Node.js (TypeScript)',
  driverName: 'mongodb',
  generate,
};
