import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToPhp } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `<?php
declare(strict_types=1);

/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json.
 * SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
 */
`;

function renderWriteConcern(plan: MigrationPlan): string {
  const w =
    plan.writeConcern.w === 'majority'
      ? "'majority'"
      : String(plan.writeConcern.w);
  return `new WriteConcern(${w}, 0, ${plan.writeConcern.journal})`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}

namespace Hvymetl\\Repositories;

use MongoDB\\Client;
use MongoDB\\Database;
use MongoDB\\Driver\\WriteConcern;

final class MongoClientFactory
{
    private static ?Client $client = null;

    public static function getDb(string $uri, string $dbName): Database
    {
        if (self::$client === null) {
            self::$client = new Client($uri, [], [
                'maxPoolSize' => ${plan.pool.maxPoolSize},
                'minPoolSize' => ${plan.pool.minPoolSize},
                'socketTimeoutMS' => ${plan.pool.socketTimeoutMS},
                'maxIdleTimeMS' => ${plan.pool.maxIdleTimeMS},
                'writeConcern' => ${renderWriteConcern(plan)},
            ]);
        }

        return self::$client->selectDatabase($dbName);
    }

    public static function closeDb(): void
    {
        self::$client = null;
    }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    '',
    'namespace Hvymetl\\Repositories;',
    '',
    'use MongoDB\\Database;',
    '',
    'final class EnsureIndexes',
    '{',
    '    public static function run(Database $db): void',
    '    {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        // ${index.reason}`);
      const unique = index.options.unique ? ", 'unique' => true" : '';
      lines.push(
        `        $db->selectCollection('${collection.name}')->createIndex(${JSON.stringify(index.keys)}, ['name' => '${index.options.name}'${unique}]);`,
      );
    }
  }
  lines.push('    }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const docblockFields = spec.fields
    .map((field) => {
      const optional = field.optional ? '|null' : '';
      return ` * @property ${bsonToPhp(field.bsonType)}${optional} $${field.name}`;
    })
    .join('\n');

  const parts: string[] = [
    `${HEADER}

namespace Hvymetl\\Repositories;

use MongoDB\\BSON\\UTCDateTime;
use MongoDB\\Collection;
use MongoDB\\Database;

/**
 * Repository for "${spec.name}" (source table: ${spec.sourceTable}).
${docblockFields}
 */
final class ${spec.pascalName}Repository
{
    private static function collection(Database $db): Collection
    {
        return $db->selectCollection('${spec.name}');
    }

    /** @return array<string, mixed>|null */
    public static function findById(Database $db, string $id): ?array
    {
        return self::collection($db)->findOne(['_id' => $id]);
    }

    /** @return list<array<string, mixed>> */
    public static function list(Database $db, ?string $afterId, int $pageSize): array
    {
        $filter = $afterId === null ? [] : ['_id' => ['$gt' => $afterId]];
        $cursor = self::collection($db)->find($filter, [
            'sort' => ['_id' => 1],
            'limit' => $pageSize,
        ]);

        return iterator_to_array($cursor, false);
    }

    /** @param array<string, mixed> $document */
    public static function insert(Database $db, array $document): void
    {
        $document['schemaVersion'] = 1;
        self::collection($db)->insertOne($document);
    }

    /** @param array<string, mixed> $fields */
    public static function updateFields(Database $db, string $id, array $fields): void
    {
        self::collection($db)->updateOne(['_id' => $id], ['$set' => $fields]);
    }`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
    public static function increment${toPascalCase(computed.field)}(Database $db, string $id, int $delta = 1): void
    {
        self::collection($db)->updateOne(
            ['_id' => $id],
            ['$inc' => [${JSON.stringify(computed.field)} => $delta]],
        );
    }`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
    /** @param array<string, mixed> $item */
    public static function pushTo${toPascalCase(arrayPlan.field)}(Database $db, string $id, array $item): void
    {
        self::collection($db)->updateOne(
            ['_id' => $id],
            [
                '$push' => [
                    ${JSON.stringify(arrayPlan.field)} => [
                        '$each' => [$item],
                        '$position' => 0,
                        '$slice' => ${arrayPlan.subsetLimit},
                    ],
                ],
            ],
        );
    }`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
    /** @param array<string, mixed> $measurement */
    public static function recordMeasurement(
        Database $db,
        string $${groupField},
        \\DateTimeInterface $measuredAt,
        array $measurement,
    ): void {
        $windowMs = ${spec.bucket.windowMinutes} * 60000;
        $measuredMs = (int) ($measuredAt->getTimestamp() * 1000);
        $windowStartMs = intdiv($measuredMs, $windowMs) * $windowMs;
        $windowStart = (new \\DateTimeImmutable('@' . (string) intdiv($windowStartMs, 1000)))->setTimezone(new \\DateTimeZone('UTC'));
        $bucketId = $${groupField} . '|' . preg_replace('/\\.\\d{3}Z$/', 'Z', $windowStart->format('Y-m-d\\TH:i:s.v\\Z'));
        self::collection($db)->updateOne(
            ['_id' => $bucketId],
            [
                '$push' => [${JSON.stringify(spec.bucket.measurementsField)} => $measurement],
                '$inc' => ['count' => 1],
                '$setOnInsert' => [
                    'schemaVersion' => 1,
                    ${JSON.stringify(groupField)} => $${groupField},
                    'windowStart' => new UTCDateTime($windowStart),
                    'windowMinutes' => ${spec.bucket.windowMinutes},
                ],
            ],
            ['upsert' => true],
        );
    }`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToPhp(spec.fields.find((field) => field.name === viaField)?.bsonType);
    parts.push(`
    /** @param ${viaType} $${viaField} @param array<string, mixed> $fields */
    public static function fanOut${toPascalCase(reference.field)}Update(
        Database $db,
        ${viaType === 'string' ? 'string' : 'mixed'} $${viaField},
        array $fields,
    ): void {
        $dotted = [];
        foreach ($fields as $key => $value) {
            $dotted[${JSON.stringify(`${reference.field}.`)} . $key] = $value;
        }
        self::collection($db)->updateMany(
            [${JSON.stringify(viaField)} => $${viaField}],
            ['$set' => $dotted],
        );
    }`);
  }

  parts.push(`
}
`);

  return parts.join('\n');
}

export const phpLanguage: RepogenLanguage = {
  id: 'php',
  label: 'PHP',
  driverName: 'mongodb/mongodb',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.php', content: renderClient(plan) },
      { relativePath: 'ensure_indexes.php', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.name}_repository.php`,
        content: renderRepository(spec),
      })),
    ];
  },
};
