import type { MigrationPlan } from '../../types.js';
import { toCamelCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToPython } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `"""Generated by hvymetl repogen. Regenerate from migration-plan.json.
SOLID · strict typing · atomic MongoDB modifiers · no read-modify-write loops."""
`;

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}

from __future__ import annotations

from pymongo import MongoClient
from pymongo.database import Database

_client: MongoClient | None = None


def get_db(uri: str, db_name: str) -> Database:
    global _client
    if _client is None:
        _client = MongoClient(
            uri,
            maxPoolSize=${plan.pool.maxPoolSize},
            minPoolSize=${plan.pool.minPoolSize},
            socketTimeoutMS=${plan.pool.socketTimeoutMS},
            maxIdleTimeMS=${plan.pool.maxIdleTimeMS},
            w=${JSON.stringify(plan.writeConcern.w)},
            journal=${plan.writeConcern.journal ? 'True' : 'False'},
        )
    return _client[db_name]


def close_db() -> None:
    global _client
    if _client is not None:
        _client.close()
        _client = None
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    '',
    'from pymongo.database import Database',
    '',
    'def ensure_indexes(db: Database) -> None:',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`    # ${index.reason}`);
      const opts = index.options.unique ? `, unique=True` : '';
      lines.push(
        `    db['${collection.name}'].create_index(${JSON.stringify(Object.entries(index.keys).map(([k, v]) => [k, v]))}, name='${index.options.name}'${opts})`,
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const className = `${spec.pascalName}Document`;
  const fieldLines = spec.fields.map((field) => {
    const annotation = bsonToPython(field.bsonType);
    const suffix = field.optional ? ' | None = None' : '';
    return `    ${field.name}: ${annotation}${suffix}`;
  });

  const parts: string[] = [
    `${HEADER}

from __future__ import annotations

from datetime import datetime
from typing import Any

from pymongo.database import Database


class ${className}(dict):
    """Typed document shape for collection '${spec.name}'."""


def _collection(db: Database):
    return db['${spec.name}']


def find_${spec.camelName}_by_id(db: Database, doc_id: str) -> dict[str, Any] | None:
    return _collection(db).find_one({'_id': doc_id})


def list_${spec.camelName}(db: Database, after_id: str | None, page_size: int) -> list[dict[str, Any]]:
    query = {'_id': {'$gt': after_id}} if after_id else {}
    return list(_collection(db).find(query).sort('_id', 1).limit(page_size))


def insert_${spec.camelName}(db: Database, document: dict[str, Any]) -> None:
    payload = {**document, 'schemaVersion': 1}
    _collection(db).insert_one(payload)


def update_${spec.camelName}_fields(db: Database, doc_id: str, fields: dict[str, Any]) -> None:
    _collection(db).update_one({'_id': doc_id}, {'$set': fields})
`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
def increment_${computed.field}(db: Database, doc_id: str, delta: int = 1) -> None:
    _collection(db).update_one({'_id': doc_id}, {'$inc': {${JSON.stringify(computed.field)}: delta}})
`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
def push_to_${arrayPlan.field}(db: Database, doc_id: str, item: dict[str, Any]) -> None:
    _collection(db).update_one(
        {'_id': doc_id},
        {'$push': {${JSON.stringify(arrayPlan.field)}: {'$each': [item], '$position': 0, '$slice': ${arrayPlan.subsetLimit}}}},
    )
`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
def record_${spec.camelName}_measurement(
    db: Database,
    ${groupField}: str,
    measured_at: datetime,
    measurement: dict[str, Any],
) -> None:
    window_ms = ${spec.bucket.windowMinutes} * 60000
    window_start = datetime.fromtimestamp(int(measured_at.timestamp() // (window_ms / 1000)) * (window_ms / 1000))
    bucket_id = f"{${groupField}}|{window_start.isoformat().replace('+00:00', 'Z')}"
    _collection(db).update_one(
        {'_id': bucket_id},
        {
            '$push': {${JSON.stringify(spec.bucket.measurementsField)}: measurement},
            '$inc': {'count': 1},
            '$setOnInsert': {
                'schemaVersion': 1,
                ${JSON.stringify(groupField)}: ${groupField},
                'windowStart': window_start,
                'windowMinutes': ${spec.bucket.windowMinutes},
            },
        },
        upsert=True,
    )
`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    parts.push(`
def fan_out_${reference.field}_update(db: Database, ${viaField}, fields: dict[str, Any]) -> None:
    dotted = {f"${reference.field}.{key}": value for key, value in fields.items()}
    _collection(db).update_many({${JSON.stringify(viaField)}: ${viaField}}, {'$set': dotted})
`);
  }

  return parts.join('\n');
}

export const pythonLanguage: RepogenLanguage = {
  id: 'python',
  label: 'Python',
  driverName: 'pymongo',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.py', content: renderClient(plan) },
      { relativePath: 'ensure_indexes.py', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.name}_repository.py`,
        content: renderRepository(spec),
      })),
    ];
  },
};
