import type { MigrationPlan } from '../../types.js';
import { toCamelCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToRuby } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `# Generated by hvymetl repogen. Regenerate from migration-plan.json.
# SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
`;

function renderWriteConcern(plan: MigrationPlan): string {
  const w =
    plan.writeConcern.w === 'majority'
      ? ':majority'
      : plan.writeConcern.w;
  return `{ w: ${JSON.stringify(w)}, j: ${plan.writeConcern.journal} }`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
require 'mongo'

module Hvymetl
  module Repositories
    module MongoClientFactory
      @client = nil

      # @param uri [String]
      # @param db_name [String]
      # @return [Mongo::Client]
      def self.get_db(uri, db_name)
        @client ||= Mongo::Client.new(
          uri,
          max_pool_size: ${plan.pool.maxPoolSize},
          min_pool_size: ${plan.pool.minPoolSize},
          socket_timeout: ${plan.pool.socketTimeoutMS} / 1000.0,
          max_idle_time: ${plan.pool.maxIdleTimeMS} / 1000.0,
          write: ${renderWriteConcern(plan)},
        )
        @client.use(db_name)
      end

      def self.close_db
        return if @client.nil?

        @client.close
        @client = nil
      end
    end
  end
end
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'module Hvymetl',
    '  module Repositories',
    '    module EnsureIndexes',
    '      # @param db [Mongo::Client]',
    '      def self.run(db)',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        # ${index.reason}`);
      const unique = index.options.unique ? ', unique: true' : '';
      lines.push(
        `        db[:${collection.name}].indexes.create_one(${JSON.stringify(index.keys)}, name: '${index.options.name}'${unique})`,
      );
    }
  }
  lines.push('      end');
  lines.push('    end');
  lines.push('  end');
  lines.push('end');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const yardFields = spec.fields
    .map((field) => `#   @!attribute ${field.name} [${bsonToRuby(field.bsonType)}]`)
    .join('\n');

  const parts: string[] = [
    `${HEADER}
require 'time'

module Hvymetl
  module Repositories
    # Repository for "${spec.name}" (source table: ${spec.sourceTable}).
    module ${spec.pascalName}Repository
      COLLECTION = :${spec.name}

${yardFields}

      # @param db [Mongo::Client]
      def self.collection(db)
        db[COLLECTION]
      end

      # @param db [Mongo::Client]
      # @param id [String]
      # @return [Hash, nil]
      def self.find_by_id(db, id)
        collection(db).find(_id: id).first
      end

      # @param db [Mongo::Client]
      # @param after_id [String, nil]
      # @param page_size [Integer]
      # @return [Array<Hash>]
      def self.list(db, after_id, page_size)
        query = after_id ? { _id: { '$gt' => after_id } } : {}
        collection(db).find(query).sort(_id: 1).limit(page_size).to_a
      end

      # @param db [Mongo::Client]
      # @param document [Hash]
      def self.insert(db, document)
        collection(db).insert_one(document.merge('schemaVersion' => 1))
      end

      # @param db [Mongo::Client]
      # @param id [String]
      # @param fields [Hash]
      def self.update_fields(db, id, fields)
        collection(db).update_one({ _id: id }, { '$set' => fields })
      end`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
      # @param db [Mongo::Client]
      # @param id [String]
      # @param delta [Integer]
      def self.increment_${computed.field}(db, id, delta = 1)
        collection(db).update_one(
          { _id: id },
          { '$inc' => { ${JSON.stringify(computed.field)} => delta } },
        )
      end`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
      # @param db [Mongo::Client]
      # @param id [String]
      # @param item [Hash]
      def self.push_to_${arrayPlan.field}(db, id, item)
        collection(db).update_one(
          { _id: id },
          {
            '$push' => {
              ${JSON.stringify(arrayPlan.field)} => {
                '$each' => [item],
                '$position' => 0,
                '$slice' => ${arrayPlan.subsetLimit},
              },
            },
          },
        )
      end`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
      # @param db [Mongo::Client]
      # @param ${groupField} [String]
      # @param measured_at [Time]
      # @param measurement [Hash]
      def self.record_measurement(db, ${groupField}, measured_at, measurement)
        window_ms = ${spec.bucket.windowMinutes} * 60_000
        window_start = Time.at((measured_at.to_f * 1000).to_i / window_ms * window_ms / 1000.0).utc
        bucket_id = "#{${groupField}}|#{window_start.iso8601.sub(/\\.\\d{3}Z$/, 'Z')}"
        collection(db).update_one(
          { _id: bucket_id },
          {
            '$push' => { ${JSON.stringify(spec.bucket.measurementsField)} => measurement },
            '$inc' => { 'count' => 1 },
            '$setOnInsert' => {
              'schemaVersion' => 1,
              ${JSON.stringify(groupField)} => ${groupField},
              'windowStart' => window_start,
              'windowMinutes' => ${spec.bucket.windowMinutes},
            },
          },
          upsert: true,
        )
      end`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToRuby(spec.fields.find((field) => field.name === viaField)?.bsonType);
    parts.push(`
      # @param db [Mongo::Client]
      # @param ${viaField} [${viaType}]
      # @param fields [Hash]
      def self.fan_out_${reference.field}_update(db, ${viaField}, fields)
        dotted = fields.transform_keys { |key| "#{reference.field}.#{key}" }
        collection(db).update_many(
          { ${JSON.stringify(viaField)} => ${viaField} },
          { '$set' => dotted },
        )
      end`);
  }

  parts.push(`
    end
  end
end
`);

  return parts.join('\n');
}

export const rubyLanguage: RepogenLanguage = {
  id: 'ruby',
  label: 'Ruby',
  driverName: 'mongo',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.rb', content: renderClient(plan) },
      { relativePath: 'ensure_indexes.rb', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.name}_repository.rb`,
        content: renderRepository(spec),
      })),
    ];
  },
};
