import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToRust } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `// Generated by hvymetl repogen. Regenerate from migration-plan.json.
// SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
`;

function rustFieldName(fieldName: string): string {
  if (fieldName === '_id') return 'id';
  return toCamelCase(fieldName);
}

function rustFieldType(bsonType: string | string[] | undefined, optional: boolean): string {
  const base = bsonToRust(bsonType);
  if (!optional) return base;
  if (base.startsWith('Option<')) return base;
  return `Option<${base}>`;
}

function renderWriteConcern(plan: MigrationPlan): string {
  const w =
    plan.writeConcern.w === 'majority'
      ? 'WriteConcern::majority()'
      : `WriteConcern::builder().w(${plan.writeConcern.w}).build()`;
  return `${w}.with_journal(${plan.writeConcern.journal})`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
use mongodb::{
    options::{ClientOptions, WriteConcern},
    Client, Database,
};
use tokio::sync::OnceCell;

static CLIENT: OnceCell<Client> = OnceCell::const_new();

pub async fn get_db(uri: &str, db_name: &str) -> mongodb::error::Result<Database> {
    let client = CLIENT
        .get_or_try_init(|| async {
            let mut options = ClientOptions::parse(uri).await?;
            options.max_pool_size = Some(${plan.pool.maxPoolSize});
            options.min_pool_size = Some(${plan.pool.minPoolSize});
            options.max_idle_time = Some(std::time::Duration::from_millis(${plan.pool.maxIdleTimeMS}));
            options.write_concern = Some(${renderWriteConcern(plan)});
            Client::with_options(options)
        })
        .await?;
    Ok(client.database(db_name))
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'use mongodb::{',
    '    bson::doc,',
    '    options::IndexOptions,',
    '    Database, IndexModel,',
    '};',
    '',
    'pub async fn ensure_indexes(db: &Database) -> mongodb::error::Result<()> {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`    // ${index.reason}`);
      const keyEntries = Object.entries(index.keys)
        .map(([field, direction]) => `"${field}": ${direction}`)
        .join(', ');
      const unique = index.options.unique ? '\n        .unique(true)' : '';
      lines.push('    db.collection::<mongodb::bson::Document>("' + collection.name + '")');
      lines.push('        .create_index(');
      lines.push('            IndexModel::builder()');
      lines.push(`                .keys(doc! { ${keyEntries} })`);
      lines.push('                .options(');
      lines.push('                    IndexOptions::builder()');
      lines.push(`                        .name("${index.options.name}".to_string())${unique}`);
      lines.push('                        .build(),');
      lines.push('                )');
      lines.push('                .build(),');
      lines.push('            None,');
      lines.push('        )');
      lines.push('        .await?;');
    }
  }
  lines.push('    Ok(())');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const structFields = spec.fields
    .map((field) => {
      const name = rustFieldName(field.name);
      const skip = field.optional ? ', skip_serializing_if = "Option::is_none"' : '';
      return `    #[serde(rename = "${field.name}"${skip})]\n    pub ${name}: ${rustFieldType(field.bsonType, field.optional)},`;
    })
    .join('\n');

  const parts: string[] = [
    `${HEADER}
use mongodb::{
    bson::{doc, Document, DateTime as BsonDateTime},
    options::UpdateOptions,
    Collection, Database,
};
use serde::{Deserialize, Serialize};

/// Repository for "${spec.name}" (source table: ${spec.sourceTable}).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ${spec.pascalName}Document {
${structFields}
}

fn collection(db: &Database) -> Collection<${spec.pascalName}Document> {
    db.collection("${spec.name}")
}

pub async fn find_${spec.camelName}_by_id(
    db: &Database,
    id: &str,
) -> mongodb::error::Result<Option<${spec.pascalName}Document>> {
    collection(db)
        .find_one(doc! { "_id": id })
        .await
}

pub async fn list_${spec.camelName}(
    db: &Database,
    after_id: Option<&str>,
    page_size: i64,
) -> mongodb::error::Result<Vec<${spec.pascalName}Document>> {
    let filter = match after_id {
        Some(id) => doc! { "_id": { "$gt": id } },
        None => doc! {},
    };
    let mut cursor = collection(db)
        .find(filter)
        .sort(doc! { "_id": 1 })
        .limit(page_size)
        .await?;
    let mut results = Vec::new();
    while cursor.advance().await? {
        results.push(cursor.deserialize_current()?);
    }
    Ok(results)
}

pub async fn insert_${spec.camelName}(
    db: &Database,
    document: ${spec.pascalName}Document,
) -> mongodb::error::Result<()> {
    let mut doc = mongodb::bson::to_document(&document)?;
    doc.insert("schemaVersion", 1);
    collection(db).insert_one(doc).await.map(|_| ())
}

pub async fn update_${spec.camelName}_fields(
    db: &Database,
    id: &str,
    fields: Document,
) -> mongodb::error::Result<()> {
    collection(db)
        .update_one(doc! { "_id": id }, doc! { "$set": fields })
        .await?;
    Ok(())
}`,
  ];

  for (const computed of spec.computedFields) {
    parts.push(`
pub async fn increment_${computed.field}(
    db: &Database,
    id: &str,
    delta: i64,
) -> mongodb::error::Result<()> {
    collection(db)
        .update_one(
            doc! { "_id": id },
            doc! { "$inc": { "${computed.field}": delta } },
        )
        .await?;
    Ok(())
}`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    parts.push(`
pub async fn push_to_${arrayPlan.field}(
    db: &Database,
    id: &str,
    item: Document,
) -> mongodb::error::Result<()> {
    collection(db)
        .update_one(
            doc! { "_id": id },
            doc! {
                "$push": {
                    "${arrayPlan.field}": {
                        "$each": [item],
                        "$position": 0,
                        "$slice": ${arrayPlan.subsetLimit},
                    }
                }
            },
        )
        .await?;
    Ok(())
}`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
pub async fn record_${spec.camelName}_measurement(
    db: &Database,
    ${groupField}: &str,
    measured_at: BsonDateTime,
    measurement: Document,
) -> mongodb::error::Result<()> {
    let window_ms = ${spec.bucket.windowMinutes} as i64 * 60_000;
    let measured_ms = measured_at.timestamp_millis();
    let window_start_ms = measured_ms - (measured_ms % window_ms);
    let window_start = BsonDateTime::from_millis(window_start_ms);
    let bucket_id = format!(
        "{}|{}",
        ${groupField},
        window_start
            .try_to_rfc3339_string()
            .unwrap_or_else(|_| window_start.timestamp_millis().to_string())
            .replacen(".000", "", 1),
    );
    collection(db)
        .update_one(
            doc! { "_id": &bucket_id },
            doc! {
                "$push": { "${spec.bucket.measurementsField}": measurement },
                "$inc": { "count": 1 },
                "$setOnInsert": {
                    "schemaVersion": 1,
                    "${groupField}": ${groupField},
                    "windowStart": window_start,
                    "windowMinutes": ${spec.bucket.windowMinutes},
                }
            },
            UpdateOptions::builder().upsert(true).build(),
        )
        .await?;
    Ok(())
}`);
  }

  for (const reference of spec.extendedReferences) {
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = rustFieldType(
      spec.fields.find((field) => field.name === viaField)?.bsonType,
      false,
    );
    parts.push(`
pub async fn fan_out_${reference.field}_update(
    db: &Database,
    ${viaField}: ${viaType},
    fields: Document,
) -> mongodb::error::Result<()> {
    let mut dotted = Document::new();
    for (key, value) in fields {
        dotted.insert(format!("${reference.field}.{}", key), value);
    }
    collection(db)
        .update_many(
            doc! { "${viaField}": &${viaField} },
            doc! { "$set": dotted },
        )
        .await?;
    Ok(())
}`);
  }

  parts.push('');
  return parts.join('\n');
}

export const rustLanguage: RepogenLanguage = {
  id: 'rust',
  label: 'Rust',
  driverName: 'mongodb',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'mongo_client.rs', content: renderClient(plan) },
      { relativePath: 'ensure_indexes.rs', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.name}_repository.rs`,
        content: renderRepository(spec),
      })),
    ];
  },
};
