import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToScala } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
 */
`;

function scalaFieldName(fieldName: string): string {
  if (fieldName === '_id') return '_id';
  return toCamelCase(fieldName);
}

function renderIndexKeys(keys: Record<string, number>): string {
  const entries = Object.entries(keys);
  if (entries.length === 1) {
    const [key, direction] = entries[0];
    return direction >= 0 ? `Indexes.ascending("${key}")` : `Indexes.descending("${key}")`;
  }
  const parts = entries.map(([key, direction]) =>
    direction >= 0 ? `Indexes.ascending("${key}")` : `Indexes.descending("${key}")`,
  );
  return `Indexes.compoundIndex(${parts.join(', ')})`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
package repositories

import org.mongodb.scala._
import org.mongodb.scala.connection.ConnectionPoolSettings
import org.mongodb.scala.model.WriteConcern
import org.mongodb.scala.connection.ClusterSettings
import com.mongodb.{ConnectionString, MongoClientSettings}

object MongoClient {

  private var client: Option[org.mongodb.scala.MongoClient] = None

  def getDatabase(uri: String, dbName: String): MongoDatabase = {
    if (client.isEmpty) {
      val settings = MongoClientSettings.builder()
        .applyConnectionString(new ConnectionString(uri))
        .applyToConnectionPoolSettings((b: ConnectionPoolSettings.Builder) =>
          b.maxSize(${plan.pool.maxPoolSize}).minSize(${plan.pool.minPoolSize})
        )
        .applyToSocketSettings(_.connectTimeout(${plan.pool.socketTimeoutMS}, java.util.concurrent.TimeUnit.MILLISECONDS))
        .writeConcern(WriteConcern(${JSON.stringify(plan.writeConcern.w)}).withJournal(${plan.writeConcern.journal}))
        .build()
      client = Some(org.mongodb.scala.MongoClient(settings))
    }
    client.get.getDatabase(dbName)
  }

  def close(): Unit = {
    client.foreach(_.close())
    client = None
  }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'package repositories',
    '',
    'import org.mongodb.scala._',
    'import org.mongodb.scala.model._',
    'import org.mongodb.scala.model.Indexes._',
    '',
    'object EnsureIndexes {',
    '',
    '  def ensureIndexes(db: MongoDatabase): Unit = {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`    // ${index.reason}`);
      const uniqueOpt = index.options.unique ? ', IndexOptions().unique(true)' : '';
      lines.push(
        `    db.getCollection("${collection.name}").createIndex(${renderIndexKeys(index.keys)}, IndexOptions().name("${index.options.name}")${uniqueOpt}).head()`,
      );
    }
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const fieldLines = spec.fields.map((field) => {
    const scalaType = bsonToScala(field.bsonType);
    const wrapped = field.optional ? `Option[${scalaType}] = None` : scalaType;
    return `  ${scalaFieldName(field.name)}: ${wrapped}`;
  });

  const parts: string[] = [
    `${HEADER}
package repositories

import org.mongodb.scala._
import org.mongodb.scala.bson._
import org.mongodb.scala.model.Filters._
import org.mongodb.scala.model.Updates._
import org.mongodb.scala.model.Sorts._
import org.mongodb.scala.model.IndexOptions
import org.mongodb.scala.model.UpdateOptions
import java.time.Instant

case class ${spec.pascalName}Document(
${fieldLines.join(',\n')}
)

object ${spec.pascalName}Repository {

  private def collection(db: MongoDatabase): MongoCollection[Document] =
    db.getCollection("${spec.name}")

  def find${spec.pascalName}ById(db: MongoDatabase, id: String): Option[Document] =
    collection(db).find(equal("_id", id)).first().headOption()

  def list${spec.pascalName}(db: MongoDatabase, afterId: Option[String], pageSize: Int): Seq[Document] = {
    val filter = afterId.map(id => gt("_id", id)).getOrElse(Document())
    collection(db).find(filter).sort(ascending("_id")).limit(pageSize).toFuture().await()
  }

  def insert${spec.pascalName}(db: MongoDatabase, document: Document): Unit = {
    val payload = document ++ Document("schemaVersion" -> 1)
    collection(db).insertOne(payload).toFuture().await()
  }

  def update${spec.pascalName}Fields(db: MongoDatabase, id: String, fields: Document): Unit =
    collection(db).updateOne(equal("_id", id), set(fields)).toFuture().await()
`,
  ];

  for (const computed of spec.computedFields) {
    const fn = toPascalCase(computed.field);
    parts.push(`
  def increment${fn}(db: MongoDatabase, id: String, delta: Long = 1): Unit =
    collection(db).updateOne(equal("_id", id), inc("${computed.field}", delta)).toFuture().await()
`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const fn = toPascalCase(arrayPlan.field);
    parts.push(`
  def pushTo${fn}(db: MongoDatabase, id: String, item: Document): Unit = {
    val pushDoc = Document(
      "$each" -> Seq(item),
      "$position" -> 0,
      "$slice" -> ${arrayPlan.subsetLimit}
    )
    collection(db).updateOne(equal("_id", id), push("${arrayPlan.field}", pushDoc)).toFuture().await()
  }
`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
  def record${spec.pascalName}Measurement(
    db: MongoDatabase,
    ${groupField}: String,
    measuredAt: Instant,
    measurement: Document
  ): Unit = {
    val windowMs = ${spec.bucket.windowMinutes}L * 60000L
    val epochMs = measuredAt.toEpochMilli
    val windowStart = Instant.ofEpochMilli((epochMs / windowMs) * windowMs)
    val bucketId = s"\${${groupField}}|\${windowStart.toString.replaceAll("\\\\.[0-9]+Z$$", "Z")}"
    val update = combine(
      push("${spec.bucket.measurementsField}", measurement),
      inc("count", 1),
      setOnInsert(
        Document(
          "schemaVersion" -> 1,
          "${groupField}" -> ${groupField},
          "windowStart" -> windowStart,
          "windowMinutes" -> ${spec.bucket.windowMinutes}
        )
      )
    )
    collection(db).updateOne(equal("_id", bucketId), update, UpdateOptions().upsert(true)).toFuture().await()
  }
`);
  }

  for (const reference of spec.extendedReferences) {
    const fn = toPascalCase(reference.field);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToScala(spec.fields.find((f) => f.name === viaField)?.bsonType);
    parts.push(`
  def fanOut${fn}Update(db: MongoDatabase, ${viaField}: ${viaType}, fields: Document): Unit = {
    val dotted = Document(fields.map { case (key, value) => s"${reference.field}.\${key}" -> value }.toSeq)
    collection(db).updateMany(equal("${viaField}", ${viaField}), set(dotted)).toFuture().await()
  }
`);
  }

  parts.push('}\n');
  return parts.join('\n');
}

export const scalaLanguage: RepogenLanguage = {
  id: 'scala',
  label: 'Scala',
  driverName: 'mongodb-scala',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'MongoClient.scala', content: renderClient(plan) },
      { relativePath: 'EnsureIndexes.scala', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.pascalName}Repository.scala`,
        content: renderRepository(spec),
      })),
    ];
  },
};
