import type { MigrationPlan } from '../../types.js';
import { toCamelCase, toPascalCase } from '../../utilities/naming.js';
import type { CollectionCodegenSpec } from '../planSpec.js';
import { buildCollectionSpecs } from '../planSpec.js';
import { bsonToSwift } from './bsonMaps.js';
import type { GeneratedFile, RepogenLanguage } from './types.js';

const HEADER = `/**
 * Generated by hvymetl repogen. Regenerate from migration-plan.json — do not edit by hand.
 * SOLID · explicit types · atomic MongoDB modifiers · no read-modify-write loops.
 */
`;

function swiftFieldName(fieldName: string): string {
  if (fieldName === '_id') return '_id';
  return toCamelCase(fieldName);
}

function renderIndexKeys(keys: Record<string, number>): string {
  const pairs = Object.entries(keys)
    .map(([key, direction]) => `("${key}", ${direction})`)
    .join(', ');
  return `[${pairs}]`;
}

function renderClient(plan: MigrationPlan): string {
  return `${HEADER}
import Foundation
import MongoSwift

enum MongoClientHolder {
    private static var client: MongoClient?

    static func getDatabase(uri: String, dbName: String) throws -> MongoDatabase {
        if client == nil {
            var options = MongoClientOptions()
            options.maxPoolSize = ${plan.pool.maxPoolSize}
            options.minPoolSize = ${plan.pool.minPoolSize}
            options.socketTimeoutMS = ${plan.pool.socketTimeoutMS}
            options.maxIdleTimeMS = ${plan.pool.maxIdleTimeMS}
            client = try MongoClient(connectionString: uri, options: options)
        }
        return client!.db(dbName)
    }

    static func close() throws {
        try client?.syncClose()
        client = nil
    }
}
`;
}

function renderIndexes(plan: MigrationPlan): string {
  const lines = [
    HEADER,
    'import Foundation',
    'import MongoSwift',
    '',
    'enum EnsureIndexes {',
    '',
    '    static func ensureIndexes(db: MongoDatabase) throws {',
  ];
  for (const collection of plan.collections) {
    for (const index of collection.indexes) {
      lines.push(`        // ${index.reason}`);
      const unique = index.options.unique ? ', unique: true' : '';
      lines.push(
        `        try db["${collection.name}"].createIndex(${renderIndexKeys(index.keys)}, options: IndexOptions(name: "${index.options.name}"${unique}))`,
      );
    }
  }
  lines.push('    }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function renderRepository(spec: CollectionCodegenSpec): string {
  const fieldLines = spec.fields.map((field) => {
    const swiftType = bsonToSwift(field.bsonType);
    const optional = field.optional ? '?' : '';
    return `    var ${swiftFieldName(field.name)}: ${swiftType}${optional}`;
  });

  const parts: string[] = [
    `${HEADER}
import Foundation
import MongoSwift

struct ${spec.pascalName}Document: Codable {
${fieldLines.join('\n')}
}

enum ${spec.pascalName}Repository {

    private static func collection(_ db: MongoDatabase) -> MongoCollection {
        db["${spec.name}"]
    }

    static func find${spec.pascalName}ById(_ db: MongoDatabase, id: String) throws -> BSONDocument? {
        try collection(db).findOne(["_id": id])
    }

    static func list${spec.pascalName}(_ db: MongoDatabase, afterId: String?, pageSize: Int) throws -> [BSONDocument] {
        var filter: BSONDocument = [:]
        if let afterId {
            filter["_id"] = ["$gt": afterId]
        }
        return try collection(db)
            .find(filter)
            .sort(["_id": 1])
            .limit(pageSize)
            .drain()
    }

    static func insert${spec.pascalName}(_ db: MongoDatabase, document: BSONDocument) throws {
        var payload = document
        payload["schemaVersion"] = 1
        _ = try collection(db).insertOne(payload)
    }

    static func update${spec.pascalName}Fields(_ db: MongoDatabase, id: String, fields: BSONDocument) throws {
        _ = try collection(db).updateOne(filter: ["_id": id], update: ["$set": fields])
    }
`,
  ];

  for (const computed of spec.computedFields) {
    const fn = toPascalCase(computed.field);
    parts.push(`
    static func increment${fn}(_ db: MongoDatabase, id: String, delta: Int64 = 1) throws {
        _ = try collection(db).updateOne(
            filter: ["_id": id],
            update: ["$inc": ["${computed.field}": delta]]
        )
    }
`);
  }

  for (const arrayPlan of spec.embeddedArrays) {
    if (!arrayPlan.subsetLimit) continue;
    const fn = toPascalCase(arrayPlan.field);
    parts.push(`
    static func pushTo${fn}(_ db: MongoDatabase, id: String, item: BSONDocument) throws {
        let pushSpec: BSONDocument = [
            "$each": [item],
            "$position": 0,
            "$slice": ${arrayPlan.subsetLimit}
        ]
        _ = try collection(db).updateOne(
            filter: ["_id": id],
            update: ["$push": ["${arrayPlan.field}": pushSpec]]
        )
    }
`);
  }

  if (spec.bucket) {
    const groupField = toCamelCase(spec.bucket.groupByColumn);
    parts.push(`
    static func record${spec.pascalName}Measurement(
        _ db: MongoDatabase,
        ${groupField}: String,
        measuredAt: Date,
        measurement: BSONDocument
    ) throws {
        let windowMs = Int64(${spec.bucket.windowMinutes}) * 60000
        let epochMs = Int64(measuredAt.timeIntervalSince1970 * 1000)
        let windowStart = Date(timeIntervalSince1970: TimeInterval((epochMs / windowMs) * windowMs) / 1000)
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime]
        let bucketId = "\\(${groupField})|\\(iso.string(from: windowStart).replacingOccurrences(of: ".000Z", with: "Z"))"
        let setOnInsert: BSONDocument = [
            "schemaVersion": 1,
            "${groupField}": ${groupField},
            "windowStart": windowStart,
            "windowMinutes": ${spec.bucket.windowMinutes}
        ]
        _ = try collection(db).updateOne(
            filter: ["_id": bucketId],
            update: [
                "$push": ["${spec.bucket.measurementsField}": measurement],
                "$inc": ["count": 1],
                "$setOnInsert": setOnInsert
            ],
            options: UpdateOptions(upsert: true)
        )
    }
`);
  }

  for (const reference of spec.extendedReferences) {
    const fn = toPascalCase(reference.field);
    const viaField = toCamelCase(reference.viaColumn);
    const viaType = bsonToSwift(spec.fields.find((f) => f.name === viaField)?.bsonType);
    parts.push(`
    static func fanOut${fn}Update(_ db: MongoDatabase, ${viaField}: ${viaType}, fields: BSONDocument) throws {
        var dotted: BSONDocument = [:]
        for (key, value) in fields {
            dotted["${reference.field}.\\(key)"] = value
        }
        _ = try collection(db).updateMany(
            filter: ["${viaField}": ${viaField}],
            update: ["$set": dotted]
        )
    }
`);
  }

  parts.push('}\n');
  return parts.join('\n');
}

export const swiftLanguage: RepogenLanguage = {
  id: 'swift',
  label: 'Swift',
  driverName: 'MongoSwift',
  generate(plan: MigrationPlan): GeneratedFile[] {
    const specs = buildCollectionSpecs(plan);
    return [
      { relativePath: 'MongoClient.swift', content: renderClient(plan) },
      { relativePath: 'EnsureIndexes.swift', content: renderIndexes(plan) },
      ...specs.map((spec) => ({
        relativePath: `${spec.pascalName}Repository.swift`,
        content: renderRepository(spec),
      })),
    ];
  },
};
